FuelLabs/fuels-rs

fuels-abigen-macro/tests/harness.rs, fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.toml, fuels-abigen-macro/tests/test_projects/complex_types_contract/src/main.sw, fuels-rs/src/contract.rs, fuels-rs/tests/calls.rs
Before the changes introduced here, using the SDK to call contracts
that takes structs as input would cause weird bugs -- it didn't really
cause a panic on the VM, but it made the access to fields within
a struct retrieve garbage data.
That was happening because in the `script_data` we sent in the tx
we weren't including a `call_data_offset` that's computed as:
```rust
let call_data_offset = script_data_offset as usize
+ ContractId::LEN + 2 * WORD_SIZE;
```
Once that was included, struct field access worked perfectly.
Curiously, this `call_data_offset` isn't needed if the input is a
primitive type (u8, bool, ...). So a conditional check that adds
the `call_data_offset` to the `script_data` iff the ABI method called
takes a struct is now in place.
This enables users to successfully perform …
=> Add support for contract calls with struct as inputs

Cargo.toml, fuels-core/src/lib.rs, fuels-core/src/signature.rs, fuels-rs/src/code_gen/abigen.rs, fuels-rs/src/code_gen/functions_gen.rs, fuels-signers/Cargo.toml, fuels-signers/src/lib.rs, fuels-signers/src/wallet/mod.rs
Two new main abstractions are introduced here: signers and wallets.
Wallets can be created from a secret key and used to sign messages and,
eventually, transactions. The signer trait is generic enough to enable
different sources to be signers, such as local wallets, trezor, ledger,
metamask, etc. These changes enable only the creation of local wallets.
All encryption is done through `secp256k1`.
Here's an example of the new capability:
```Rust
// Generate your secret key
let mut rng = StdRng::seed_from_u64(2322u64);
let mut secret_seed = [0u8; 32];
rng.fill_bytes(&mut secret_seed);
let secret =
SecretKey::from_slice(&secret_seed)
.expect("Failed to generate random secret!");
// Create a new local wallet with the newly generated key
let wallet = LocalWallet::new_from_private_key(secret)?; …
```
=> Add initial abstraction for signers and wallets

fuels-abigen-macro/tests/test_projects/call_empty_return/Forc.toml, fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.toml, fuels-abigen-macro/tests/test_projects/contract_output_test/Forc.toml, fuels-abigen-macro/tests/test_projects/contract_test/Forc.toml, fuels-abigen-macro/tests/test_projects/lib-core/Forc.toml, fuels-abigen-macro/tests/test_projects/lib-std/Forc.toml, fuels-abigen-macro/tests/test_projects/library_test/Forc.toml, fuels-abigen-macro/tests/test_projects/script_test/Forc.toml, fuels-abigen-macro/tests/test_projects/simple_script/Forc.toml, fuels-rs/tests/calls.rs
- fix: update licence and authors in examples and tests manifests
- test: fetch git repository for sway std and core lib in manifests
This closes #37 and #38.
=> fix: update dependencies and licences in test/examples

fuels-rs/src/contract.rs, fuels-rs/src/script.rs, fuels-rs/tests/calls.rs
`[[tx-input]]` should never have been used outside of the Sway repo anyways. This PR removes the use of it in the SDK.
=> Remove use of `[[tx-input]]` from manifest.

fuels-rs/src/contract.rs, fuels-rs/tests/calls.rs
The SDK was setting values for UTXO ID, state root, and balances root. These are not meant to be set by the SDK, but rather malleated by the block producer (i.e. a node).
Also removed the logic to handle input index, since it wasn't actually used. Added a TODO to allow passing in multiple contracts that will each have an input-output pair, at which point the input index will be needed. Filed #59 to track this feature.
=> Remove malleable fields from being set by the SDK.

fuels-rs/src/code_gen/custom_types_gen.rs
This PR implements tests for the custom types generation from the ABI. 
It also specifies that `structs` inside `enums` and `enums` inside `structs` are not yet implemented.
This is part of solving #6.
=> test: test custom types ABI generation

fuels-abigen-macro/tests/harness.rs, fuels-rs/src/contract.rs
- Introduce the CallResult struct, that holds the call return in its
`value` field, and the receipts in the `receipts` field.
- This closes issue #35
=> feat: return receipts in data returned by contract calls

fuels-abigen-macro/tests/harness.rs, fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml, fuels-abigen-macro/tests/test_projects/two-structs/Forc.toml, fuels-abigen-macro/tests/test_projects/two-structs/abi.json, fuels-abigen-macro/tests/test_projects/two-structs/src/main.sw, fuels-abigen-macro/tests/test_projects/two-structs/tests/harness.rs, fuels-core/src/code_gen/abigen.rs, fuels-core/src/code_gen/custom_types_gen.rs, fuels-core/src/code_gen/functions_gen.rs
Fixes https://github.com/FuelLabs/fuels-rs/issues/77. 
Also simplifies some things related to custom types.
=> Fixes ambiguity on two diff structs with same arg name

.github/workflows/ci.yml
Our crate publishing step is still blocked by this PR: https://github.com/katyo/publish-crates/pull/394. 
However, as shown by `katyo` (author of `publish-crates`), one can work around the cyclic deps issue by using the `--no-verify` flag, which is equivalent to the `--no-verify` flag in here: https://doc.rust-lang.org/cargo/commands/cargo-publish.html. Here's the concrete example linked by the author: https://github.com/DelSkayn/rquickjs/blob/master/.github/workflows/ci.yml#L349. 
This PR enables that in order to try and unblock us for the release of the `v0.3.0`.
=> Add --no-verify flag to publish crate action

fuels-abi-cli/src/main.rs, fuels-abigen-macro/src/lib.rs, fuels-abigen-macro/tests/harness.rs, fuels-abigen-macro/tests/takes_ints_returns_bool.json, fuels-core/src/code_gen/abigen.rs, fuels-core/src/code_gen/functions_gen.rs
This PR refactors the function `expand_function_arguments` to avoid checking for template arguments (`gas_, amount_, color_`) every time. It propagates the argument up to the abigen macro so user can chose if the expansion should check for types or not. 
It closes #75
=> refactor: add an argument to enable strict argument checking in abigen macro

fuels-signers/src/lib.rs, fuels-signers/src/signature.rs, fuels-signers/src/wallet/mod.rs
Adds transaction signing to the wallet API: 
```rust
let wallet = LocalWallet::new_from_private_key(secret).unwrap();
let input_coin = Input::coin(
// ...
);
let output_coin = Output::coin(
// ..
);
let tx = Transaction::script(
// ..
);
let signature = wallet.sign_transaction(&tx).await.unwrap();
```
Closes https://github.com/FuelLabs/fuels-rs/issues/69.
=> Implement transaction signing

fuels-core/Cargo.toml, fuels-core/src/source.rs
This removes the use of the `Url` crate for loading ABI .json files. This approach was incompatible with Windows paths so has been removed in order to support that OS. [See here](https://github.com/FuelLabs/fuels-rs/issues/93) for more discussion on this issue.
closes #93
=> remove the Url crate from fuels-core

fuels-abigen-macro/tests/harness.rs, fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.toml, fuels-abigen-macro/tests/test_projects/revert_transaction_error/abi.json, fuels-abigen-macro/tests/test_projects/revert_transaction_error/src/main.sw, fuels-abigen-macro/tests/test_projects/revert_transaction_error/tests/harness.rs, fuels-contract/src/contract.rs, fuels-contract/src/errors.rs, fuels-contract/src/script.rs
* Previously, a reverting transaction would not be captured by the SDK.
* This closes #102 .
=> feat: capture error from reverting transactions in the SDK

.github/workflows/ci.yml
Currently the crate publishing action is complaining about this reasonable use-case here: https://github.com/FuelLabs/fuels-rs/blob/master/fuels-signers/Cargo.toml#L31
@Voxelot will patch the action itself to accept this use-case, but for now we'll bring back the `no-verify` option so we can publish a new release.
=> Bring back no-verify temporarily

fuels-signers/Cargo.toml
Removes a `fuels-signers` dev dependency to itself, which might be causing crate publishing issues.
=> Remove dev dependency

fuels-abi-cli/src/main.rs, fuels-contract/src/contract.rs, fuels-contract/src/script.rs, fuels-core/src/abi_decoder.rs, fuels-core/src/abi_encoder.rs, fuels-core/src/lib.rs, fuels-core/src/source.rs, fuels-core/src/types.rs
This PR closes #76 so it's easier to detect when you trigger a clippy warning.
=> style: fix clippy warnings

Cargo.lock, fuels-abigen-macro/Cargo.toml, fuels-abigen-macro/tests/test_projects/foo-caller-contract/Cargo.toml, fuels-abigen-macro/tests/test_projects/foo-contract/Cargo.toml, fuels-abigen-macro/tests/test_projects/two-structs/Cargo.toml, fuels-contract/Cargo.toml, fuels-contract/src/contract.rs, fuels-core/Cargo.toml, fuels-signers/Cargo.toml, fuels-signers/src/lib.rs, fuels-signers/src/provider.rs, fuels-signers/src/signature.rs, fuels-signers/src/util.rs, fuels-signers/src/wallet.rs
`fuel-core` `0.4.x` brought in lots of changes, such as:
- Renaming `color` to `asset id`;
- Some structural changes to the GraphQL schema;
- Some changes to its types;
- And some more.
This PR makes the necessary changes to support these changes. Also, `Hasher` was moved from `fuel-tx` to `fuel-crypto`, so we introduce `fuel-crypto` as a dependency to `fuels-rs`. 
Closes https://github.com/FuelLabs/fuels-rs/issues/140.
=> Update to `fuel-core` 0.4

fuels-abigen-macro/tests/harness.rs, fuels-core/src/code_gen/abigen.rs, fuels-core/src/errors.rs, fuels-core/src/json_abi.rs
This PR closes #111 by fixing the ABI parsing of the array type from `T[n]` to `[T; n]`.
It also refactors the parsing of `str[n]` parameters and implements tests for both parsing.
=> fix: support the new Sway array type format

fuels-core/src/json_abi.rs, fuels-signers/src/provider.rs, fuels-signers/src/wallet.rs
Remove stragglers missed in #147.
Remaining instances of the word `color` should only be as ABI parameters, which will be removed with #13, and a single use of the stdlib `ETH_COLOR` constant, which can be changed in the stdlib first.
=> Rename color to asset ID.

fuels-core/src/code_gen/abigen.rs
=> fix: do not output to stdout when `--show-output` is not enabled

fuels-contract/src/contract.rs, fuels-signers/src/signature.rs
* This PR closes #130 by signing transactions before submitting them to the client.
* The "sign transactions before submission" portion isn't tested because I struggled 
to find a way to meaningfully test the whole workflow. Feel free to chime in with ideas
if you think this is important, but to me the unit tests are enough.
=> feat: sign transactions before submitting them to the client

fuels-contract/src/contract.rs
Introduces a new non-breaking API `append_variable_outputs(num: u64)` that appends `num` `Output::Variable`s to the crafted transaction. 
This is a builder method, like `call_params()` and `tx_params()`:
```rust
let response = instance
.get_msg_amount()
.tx_params(tx_params)
.call_params(call_params)
.append_variable_outputs(10)
.call()
.await
.unwrap();
```
Closes https://github.com/FuelLabs/fuels-rs/issues/171.
=> Support setting variable outputs in contract calls

fuels-abigen-macro/tests/harness.rs, fuels-contract/src/contract.rs, fuels-core/src/constants.rs
Enable forwarding amount of size up to `u64` in contract calls.
Before, we were forcing the amount to be an `Immediate12`, which doesn't work for many use cases where we would need a `u64`. Passing a bigger number to the amount being forwarded would cause an overflow. 
closes: #174
=> feat: Support forwarding amounts of size up to `u64` in contract calls

fuels-contract/src/contract.rs
Fixes #182
Prior to signing, _a_ witness was needed so that the input coin could point to a witness. Hence the existence of a zero-witness. Now with signing, that zero-witness is unnecessary.
=> Remove extra (incorrect) witness.

fuels-contract/src/contract.rs, fuels-signers/src/util.rs, fuels-signers/src/wallet.rs
This PR turns on the UTXO validation flag (from the `fuel-core` node), which enables full validation of transactions. 
So far, the only thing that broke due to this flag was the contract deployment, which was easily fixed by correcting the witness index. 
Shockingly, nothing else seemed to break. Though we've been working on adding proper signatures to the transaction for a while now. However, up until now, it had never been actually tested. But with the UTXO validation flag, [the signatures are actually tested](https://github.com/FuelLabs/fuel-tx/blob/master/src/transaction/validation.rs#L32).
Closes https://github.com/FuelLabs/fuels-rs/issues/188.
=> Turn on UTXO validation in tests

fuels-abigen-macro/tests/harness.rs, fuels-core/src/code_gen/abigen.rs, fuels-core/src/lib.rs
Closes https://github.com/FuelLabs/fuels-rs/issues/99 (you can also find more context in that issue).
This PR enables support for the Sway-native types `ContractId` and `Address` in the ABI methods. This means no need to create unergonomic wrappers. 
Before:
```Rust
// This is the contract id we want to pass around.
let id = Contract::deploy(&compiled, &provider, &wallet, TxParameters::default())
.await
.unwrap();
// We have to create these ugly wrappers to make it work.
let target = testfuelcoincontract_mod::ContractId { value: id.into() };
let asset_id = testfuelcoincontract_mod::ContractId { value: id.into() };
// ...
let mut balance_result = instance
.get_balance(target.clone(), asset_id.clone())
.call()
.await
.unwrap();
```
Now:
```Rust
// This is the contract id we want to pass …
```
=> Accept Sway-native types directly and without wrappers

.github/workflows/ci.yml, Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/code_gen/custom_types_gen.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-types/Cargo.toml, packages/fuels-types/src/lib.rs, tools/fuels-abi-cli/Cargo.toml, tools/fuels-abi-cli/src/main.rs
This moves the `JsonABI` type along with the associated `Function` and `Property` types from `sway-types` into a new minimal `fuels-types` crate.
By moving these from `sway-types` upstream to the `fuels-rs` repo, we can resolve the remainder of the cyclic dependency between the `sway` and `fuels-rs` repositories.
I think also semantically it makes a little more sense for the Rust representation of these ABI-specific types to be declared under the Rust SDK, and for Sway to depend on these rather than vice versa.
The `fuels-core` crate now depends on these types via the new `fuels-types` crate. The unused `sway-utils` dependency has been removed.
As an immediate follow-up to `fuels-types` landing and getting published to crates.io, we should remove these types from the `sway-types` crate …
=> Add `fuels-types` minimal crate for declaring serializable ABI types. Resolves the cycle between `fuels-rs` and `sway` repos.

Cargo.toml, packages/fuels-abigen-macro/Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/src/json_abi.rs, tools/fuels-abi-cli/Cargo.toml
Closes #137
Tested with `rustfix`, i.e. `cargo fix --edition`, as well as `cargo test --all-targets --all-features`. Removed unnecessary code for 2021 edition.
Trying to look around all the repos to see how stuff works before I can make any useful contributions lol
=> Move to 2021 Rust #137

packages/fuels-contract/src/contract.rs
* Some leftovers remained from when we didn't support `Tuple` as output
parameters.
=> fix: enforce accepting only one output parameter

packages/fuels-abigen-macro/Cargo.toml, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-rs/Cargo.toml, packages/fuels-rs/src/lib.rs
If you're up for this @digorithm, I'm thinking we should land this sooner than later in case someone snatches up `fuels` on crates.io.
Closes #225
=> Rename `fuels-rs` crate to `fuels`

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/contract_logdata/.gitignore, packages/fuels-abigen-macro/tests/test_projects/contract_logdata/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/contract_logdata/src/main.sw, packages/fuels-contract/src/contract.rs, packages/fuels-core/src/lib.rs
This PR closes #214.
- feat: decode log data as hex strings in `CallResponse` property
- test: add contract for testing `logd` opcode
- test: add test for `LOGD` decoding in harness
=> feat: decode `LOGD` data in `CallResponse`

Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-signers/src/provider.rs
fixes: #250 
Running a local copy of fuel-core from fuel-signers::Provider is purely a convenience function for local testing. However, when using the SDK in production services, we shouldn't be including the extra dependencies from fuel-core as they're unnecessary when calling a remote fuel-core node.
=> make fuel-core optional in fuels-signers

.github/workflows/ci.yml
Addresses @mitchmindtree's concern about ensuring backwards compatibility with the rust-version specified in the fuels Cargo.toml.
If the rust-version gets updated in fuels, ci will break unless its version is also updated.
=> Ensure minimum supported rust version is verified in CI

docs/src/getting-started/basics.md, docs/src/getting-started/setup.md
Updates the mdbook to include and match all that's new to the SDK.
=> Update the Fuel Rust SDK book to match latest development

.github/workflows/ci.yml, packages/fuels/Cargo.toml
This ensures that users are warned in the case that their installed Rust version predates the version required by `fuels-rs`.
This should be particularly useful for users building `forc`-generated test harnesses, as I believe we've already had a couple of reports of strange compile errors that just required a Rust version update.
You can find documentation on this field [here][1].
[1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
---
Originally I had planned on exposing this minimum required Rust version from a function in the crate root [like so](https://github.com/mitchmindtree/fuels-rs/commit/17ad3fd16d48f3c50d688e1333ac8eb8dc59dbac). The idea was that `forc` could use this function to specify the necessary `rust-version` field in the generated test …
=> Specify minimum supported Rust version in `fuels-rs` manifest

.github/workflows/ci.yml, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw, packages/fuels-contract/src/contract.rs, packages/fuels-core/src/lib.rs
Closes https://github.com/FuelLabs/fuels-rs/issues/239.
`forc` `0.12` made some updates to the way different data types are handled, as seen on the above issue. 
This PR makes the necessary changes to support these updates. This also includes updating the CI to use `forc` `0.12`.
=> Update type handling and add support for forc `0.12.x`

packages/fuels-abigen-macro/tests/harness.rs
* The tests were removed by mistake in 8df82cf7e924b9afbe7ec58f9b032e34d315b5ffa
=> test: add tests for `LOGD` decoding in harness

packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/lib.rs, packages/fuels-core/src/constants.rs, packages/fuels-core/src/lib.rs, packages/fuels-core/src/parameters.rs, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels/src/lib.rs
This PR introduces the addition of `TxParameters` to the `wallet.transfer()` API. Enabling the user to configure the `TxParameters` in a transfer call, which was previously hardcoded.
Now, transfers look like this:
```Rust
let receipts = wallet
.transfer(&target.address(), amount, Default::default(), /* new */ TxParameters::default())
.await
.unwrap();
```
Also, I've moved `parameters.rs` from `fuels-contract` to `fuels-core`, to avoid a cyclic dependency problem now that `fuels-signers` need `parameters`, the same for `fuels-contract` needing `parameters`.
Closes https://github.com/FuelLabs/fuels-rs/issues/270.
=> Add `TxParameters` to transfer functionality

docs/src/getting-started/setup.md
Update setup docs to also include `fuel-tx = 0.9` and bump `fuels-abigen-macro` and `fuels` versions from 10 to 12
=> Update getting started/setup doc

packages/fuels-abigen-macro/tests/harness.rs
fuel-core 0.6.4 made some changes to error formatting that broke an SDK test.
=> update test due to breaking error format change in fuel-core

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/use_enum_input/src/main.sw, packages/fuels-core/src/abi_decoder.rs, packages/fuels-core/src/abi_encoder.rs, packages/fuels-core/src/code_gen/custom_types_gen.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-core/src/lib.rs, packages/fuels-core/src/types.rs
This PR closes #231 by implementing support for unit type variants in `Enums`.
=> feat: support unit type variants in `Enum`

packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/code_gen/custom_types_gen.rs, packages/fuels/src/lib.rs
This fixes the issue:
```
Error[E0433]: failed to resolve: use of undeclared crate or module `fuels_core`
--> tests/harness.rs:7:1
|
7 | abigen!(MyContract, "out/debug/bimbam-abi.json");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `fuels_core
```
This was happening because the trait `Detokenize` and one of the errors were being pulled from `fuels_core` without actually pulling `fuels_core` as a dependency. This PR adds both `Detokenize` and the mentioned error in the prelude and solves the issue above.
=> Fix fuels core dependency

docs/src/getting-started/basics.md
Updated basics.md for documenting that append_variable_outputs is also needed for mint_to_address #300
=> Clarify appending variable outputs

docs/src/getting-started/basics.md, docs/src/getting-started/setup.md, packages/fuels-abigen-macro/Cargo.toml, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-contract/Cargo.toml, packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/script.rs, packages/fuels-core/Cargo.toml, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-signers/Cargo.toml, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/Cargo.toml, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/signers.rs
- Updated fuel-core to 0.8, dealing with any breaking API changes related to `Input::coin` becoming `Input::coin_signed`. This will make the SDK compatible with the new UTXO predicate feature in fuel-core.
- Reduced the number of direct deps fuels-rs has to manage by leveraging re-exported types wherever possible.
- This resolved an issue where some fuels packages depended on different major versions of fuel-asm. Using re-exported types will prevent missed version bumps in the future.
- It also simplifies the number of dependencies that SDK consumers (sway apps) need to maintain, allowing them to simply import `fuels` for all their needs. 
- The only place where a direct dependency above fuel-gql-client couldn't be removed was in fuels-core. This is because it's meant to be a lightweight …
=> fuel-core 0.8 upgrade (predicates)

packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml
Resolves this failing CI: https://github.com/FuelLabs/fuels-rs/actions/runs/2393556289
Adds the `random` feature for `fuel-crypto` in `fuels-signers` and removes unused `fuel-crypto` in `fuels-test-helpers`.
=> Fix crypto dep random feature.

docs/src/getting-started/basics.md, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/script.rs, packages/fuels-core/src/errors.rs
This PR closes #295 by changing the `ContractCallError` variant to log the
receipts in case of reverting or panicking contract calls.
=> feat: log receipts when contract call panics or reverts

.github/workflows/ci.yml, .github/workflows/scripts/verify_tag.sh, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-signers/src/wallet.rs
We were having build failures during cargo publish dry-run that weren't caught earlier in CI since the build command was unifying features across all crates (including test-helpers). [`cargo make`](https://github.com/sagiegurari/cargo-make) comes with sane default configurations for building the repo in a way that will prevent this from happening in the future.
edit: while cargo make works, we can speed things up a lot by using cargo check on each package in parallel to skip linking. Updated the PR to that approach which cuts the CI pipeline time in half.
=> Disable feature unification in CI builds

docs/src/getting-started/basics.md, examples/contracts/src/lib.rs, packages/fuels/Cargo.toml, packages/fuels/src/lib.rs
Related: #342.
- re-export `fuel_core` and `fuel_gql_client` from `fuels`
- create `instantiate_client` test in `examples/contracts` (could be moved later)
- include `instantiate_client` code in `getting-started/basics.md`
> Issue
> - [fuellabs.github.io/fuels-rs](https://fuellabs.github.io/fuels-rs/latest/index.html) is linked as the fuels-rs homepage on Github
> - In the [Getting Started section](https://fuellabs.github.io/fuels-rs/latest/getting-started/setup.html) of the book, only fuel-tx, fuels-abigen-macro, and fuels are referenced as dependencies
> - However, when looking at the [Basic Usage](https://fuellabs.github.io/fuels-rs/latest/getting-started/basics.html) section, the example includes fuel_core
> 
> Expected result
> - A proper fuel-core dependency is specified in the …
=> docs(examples): add instantiate_client example

packages/fuels-contract/src/errors.rs, packages/fuels-core/src/abi_decoder.rs, packages/fuels-core/src/errors.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-core/src/types.rs
This commit should resolve https://github.com/FuelLabs/fuels-rs/issues/204
The InvalidData error type now provides more context. I have gone through all instances and updated the error messages accordingly.
Additionally, I have found a bug where the functions
`pub fn tokenize_struct(&self, value: &str, params: &[ParamType]) -> Result<Token, Error> {`
and 
`pub fn tokenize_array<'a>(&self, value: &'a str, param: &ParamType) -> Result<Token, Error> {`
would not return an error if there were excess opening brackets. For example: 
`let values: Vec<String> = vec!["((42, true)".to_string()];`
would previously pass through the tokenize_struct function and return an error only at the end assertion in the test.
Now both functions return appropriate error messages.
Could somebody please go through …
=> feat: add context to InvalidData error

packages/fuels/src/lib.rs
Should fix some build problems on #355. Investigating why CI was green in the first place.
Re @Salka1988
=> fix(examples): add Config from fuel-core to prelude

examples/contracts/Cargo.toml, examples/wallets/Cargo.toml
Context: https://github.com/FuelLabs/fuels-rs/runs/6780831010?check_suite_focus=true
The CI is trying to publish one of the examples -- it shouldn't. Plus some extra metadata.
=> Fix examples cargo TOML

.github/workflows/ci.yml, Cargo.toml, packages/fuels-core/src/code_gen/abigen.rs, packages/wasm-tests/.cargo/config.toml, packages/wasm-tests/Cargo.toml, packages/wasm-tests/src/lib.rs
Opening as a draft for now to get some eyes on it. There were some build issues on my machine that looked like they may be config related, so I wanted to see if it passes CI.
It looks like this is about all I need in order to make things work in WASM. As long as the codegen output `use` statements that are from `fuels_core`, I think it will compile fine.
I've added a separate directory for WASM tests, since I have to override the default build target. I added the `.cargo/config.toml` to set it to wasm32-unknown-unkown.
I believe this will address #317 and #318
=> Wasm support

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/tuples/src/main.sw, packages/fuels-core/src/code_gen/functions_gen.rs
This fixes the following case:
```Rust
fn tuple_with_b256(p: (b256, u8)) -> (b256, u8);
```
```Rust
let id = *ContractId::zeroed();
let my_b256_u8_tuple: ([u8; 32], u8) = (id, 10);
let response = instance
.tuple_with_b256(my_b256_u8_tuple)
.call()
.await
.unwrap();
assert_eq!(response.value, my_b256_u8_tuple);
```
Previously, the generated function looked like this:
```
pub fn tuple_with_b256(&self, value: (b256, u8)) -> ContractCall<()>
```
But `b256` isn't a Rust type, this needs to be properly expanded to `[32; u8]`. 
This PR improves how the components inside a tuple are being expanded, fixing this issue.
=> fix: improve fn signature generation for tuples

packages/fuels-core/src/json_abi.rs
This PR should close https://github.com/FuelLabs/fuels-rs/issues/359
I have added tests to cover expected tokenization errors for the built-in types, tuples, arrays and structs.
I have also added a new error for the `b256` type, when the hex encoding doesn't have the required length.
=> feat: extend abi json cli tests to cover expected errors

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/enum_as_input/src/main.sw, packages/fuels-core/src/code_gen/custom_types_gen.rs, packages/fuels-core/src/code_gen/functions_gen.rs
Suppose the following two structs in Sway:
```Rust
pub struct Campaign {
author: Identity,
asset: ContractId,
beneficiary: Identity,
claimed: bool,
deadline: u64,
state: u64, 
target_amount: u64,
total_pledge: u64,
}
pub struct Campaigns {
active: [u64; 1],
completed: [u64; 1],
}
```
Given the current state of the SDK, this would lead to this error:
That's because `Campaigns` was being turned into `Campaign` due to `Inflector`'s `.to_class_case()`, and then conflicting with the original `Campaign`. 
Fiddling with the casing chosen by the Sway user is bad and not wanted, whatever the Sway user decides (and the _compiler_ allows) should be what is generated by the SDK, otherwise, there will be a discrepancy between what the user chose and what the SDK is generating, which isn't good.
This …
=> fix: do not modify custom type names

packages/fuels-core/src/code_gen/custom_types_gen.rs
Similar to https://github.com/FuelLabs/fuels-rs/pull/392. 
This was recently added to handle nested enums but we overlooked another use of `.to_class_case()`.
=> fix: do not modify inner enum name in a nested enum

docs/src/getting-started/setup.md, docs/src/getting-started/type-safe-bindings.md, examples/contracts/Cargo.toml, examples/contracts/src/lib.rs, packages/fuels-abigen-macro/src/lib.rs, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels/src/lib.rs
I inserted `abigen!()` macro into the `fuel` library so users don't have to import the `fuels-core-abigen` library into Cargo.toml of their tests to use `abigen!()` macro.
From :
```rust
[project]
name = "zule"
version = "0.1.0"
authors = ["salka1988"]
edition = "2021"
license = "Apache-2.0"
[dependencies]
fuels = "0.14"
fuels-abigen-macro = "0.14"
tokio = { version = "1.12", features = ["rt", "macros"] }
[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
```
To:
```rust
[project]
name = "zule"
version = "0.1.0"
authors = ["salka1988"]
edition = "2021"
license = "Apache-2.0"
[dependencies]
fuels = "0.14"
tokio = { version = "1.12", features = ["rt", "macros"] }
[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
```
```
=> add abigen to fuels Cargo.Toml

Cargo.toml, docs/src/getting-started/basics.md, docs/src/getting-started/type-safe-bindings.md, docs/src/getting-started/wallets.md, docs/src/workspaces/fuels-abigen-macro.md, examples/contracts/src/lib.rs, examples/rust_bindings/Cargo.toml, examples/rust_bindings/src/abi.json, examples/rust_bindings/src/lib.rs, examples/rust_bindings/src/rust_bindings_formatted.rs, examples/wallets/src/lib.rs, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/token_ops/src/main.sw, packages/fuels-contract/src/contract.rs, packages/fuels-core/src/constants.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/script.rs
This PR closes #342.
- All examples in `The Book` now use the `examples` directory. Some
reorganization of that structure might/should happen down the road, but for
now the idea is to just move forward with using only tested code in `The
Book`.
Apologies in advance, this PR will probably be *hell* to review because there are snippets distributed everywhere lol :sweat_smile:
=> docs: migrate all examples

.github/workflows/ci.yml, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/call_empty_return/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/complex_types_contract/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/contract_test/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/enum_encoding/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/foo_caller_contract/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/multiple_read_calls/src/main.sw, packages/fuels-abigen-macro/tests/test_projects/nested_enums/src/main.sw, packages/fuels-contract/src/contract.rs, packages/fuels-core/src/abi_decoder.rs, packages/fuels-core/src/abi_encoder.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels-core/src/encoding_utils.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-core/src/lib.rs
closes: #390 
The sway compiler, since the release of Forc 16.0.0, includes an optimization with regards to enums that only have unit types for variants.
Such enums are to be encoded in only one word that contains their discriminant.
This PR also contains the necessary fixes to our Sway files thanks to @digorithm 
The cleanest way of looking at this is to say that enums with only unit variants will not have their unit variant encoded at all. This is preferable to wording like 'units are 0B in enums, 1 B elsewhere'. Although the 'elsewhere' part can be debated since the SDK doesn't support using Units anywhere else. This phrasing was translated into code.
Although the changes are covered by unit tests, there is an e2e test that will safeguard us against regressions in the sway compiler -- …
=> Encoding of an enum with all unit variants (#390)

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-abigen-macro/tests/test_projects/nested_structs/src/main.sw, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/constants.rs
Fixes https://github.com/FuelLabs/fuels-rs/issues/414.
Custom types in the JSON ABI containing the strings `Address` or `ContractID` were being ignored and not generated. That's because we don't re-generate Sway-native types, but the check for it was buggy: we checked if it contained, not if it's an exact match.
For instance, `struct Address` in your JSON ABI would be correctly ignored. `struct MemoryAddress` would be _incorrectly_ ignored because it contains `Address` in it. 
This PR changes the check logic and fixes this issue.
=> fix: custom types containing reserved keyword

packages/fuels-abigen-macro/Cargo.toml
Currently, we're seeing the following error when trying to publish the `0.16` crate: 
That's because we're adding a `fuels` feature flag to `fuels-abigen-macro` but not having `fuels` as a `dependencies`, only as `dev-dependencies`. Adding `fuels` to `dependencies` breaks it all because it introduces a circular dependency issue.
=> fix: broken crate publishing CI due to abigen feature flag

examples/contracts/src/lib.rs, examples/rust_bindings/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-contract/src/contract.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/script.rs, packages/fuels-test-helpers/src/signers.rs
Closes: https://github.com/FuelLabs/fuels-rs/issues/312
Changed the `launch_provider_and_get_single_wallet` to `launch_provider_and_get_wallet`.
Deleted `launch_provider_and_get_wallets` and `launch_custom_provider_and_get_single_wallet`.
Instead, we are going to use `launch_custom_provider_and_get_wallets` where we customize both the provider and wallet.
=> refactor: change the launch functions and wallet setup

docs/src/getting-started/basics.md
In my last PR https://github.com/FuelLabs/fuels-rs/pull/422 I forgot to update the fuels-rs book.
Luckily, we need to update only one mention of the refactored functions as the examples were already updated.
=> doc: update launch functions reference after refactor

examples/contracts/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-core/src/abi_decoder.rs, packages/fuels-core/src/abi_encoder.rs, packages/fuels-core/src/encoding_utils.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/script.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/395
All tests in `fuels-rs` that used unwrap() on a Result<> now have a Result<> return type.
As the issue was unassigned, I took it but later I saw that @thdaraujo already did the `harness.rs` file.
Do we have a way to assign issues to people outside of the organization ?
=> refactor: tests return Result<> when applicable

packages/fuels-test-helpers/src/node.rs
When running `forc test` there are some spammy console logs originating from fuel_core.
This will void `stdin` and `stdout` stream and should remove those logs (`stderr` is left for better diagnostic).
=> Set fuel-core stdin/stdout stream to null

.github/workflows/ci.yml
This is actually not useful and prevents some tests from running as they should.
=> ci: remove the `--no-default-features` flag for running tests

packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/code_gen/custom_types_gen.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels-core/src/json_abi.rs, packages/fuels-core/src/utils.rs, packages/fuels-types/src/function_selector.rs, packages/fuels-types/src/lib.rs, packages/fuels-types/src/utils.rs
* These methods will ultimately be used inside the Sway repository, and
they didn't use the ABIParser fields.
=> refactor: move function selector methods out of `ABIParser` struct

packages/fuels-types/src/parse_param.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/str_in_array/Forc.toml, packages/fuels/tests/test_projects/str_in_array/src/main.sw
closes: https://github.com/FuelLabs/fuels-rs/issues/505
There was a bug in the parsing logic of arrays and strings.
I have taken the test_project created by @QuinnLee and removed the part with primitive types inside arrays, as we have tested them already.
=> fix: string in array parsing

docs/src/providers/querying.md, examples/providers/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-contract/src/script.rs, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/signers.rs
* Previously, the `get_coins` methods only retrieved BASE_ASSET_ID
coins. Now it retrieves coins of the argument `asset_id`.
=> refactor: add an `asset_id` argument to `get_coins` API

.github/workflows/ci.yml, packages/fuels/tests/harness.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/509
The compiler error was fixed and we can now run the full test.
=> fix: enable skipped test for strings in arrays

packages/fuels-signers/Cargo.toml, packages/fuels-signers/src/wallet.rs
This removes the use of `bip32/39` dependencies from the SDK and moves the mnemonic creation logic to `fuel-crypto`.
=> Use `fuel-crypto` for secret key generation from mnemonic

packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/node.rs
* This PR closes #495 by adding the `silent` option for running a Fuel node, which is enabled by default.
=> fix: remove spam from `fuel-core` when running tests

docs/src/SUMMARY.md, docs/src/getting-started/managing-wallets.md, docs/src/wallets/access.md, docs/src/wallets/signing.md, examples/cookbook/src/lib.rs, examples/providers/src/lib.rs, examples/rust_bindings/src/rust_bindings_formatted.rs, examples/wallets/src/lib.rs, packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/script.rs, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/code_gen/flat_abigen.rs, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/signers.rs, packages/fuels/src/lib.rs, packages/fuels/tests/harness.rs
This PR was motivated by work @kayagokalp and I are doing on the
following:
https://github.com/FuelLabs/sway/issues/2413
We noticed that in order to perform any operations using a `Wallet`, the
private key must be known, even if those operations were simply
retrieving asset balances or a list of transactions.
This PR aims to draw a clearer distinction between Wallet methods that
require access to a private key and those that do not. The idea is to
encourage users of the API to be conscious of when their wallet is in an
unlocked state (i.e. their private key resides in memory) and when it
does not.
To achieve this, we turn `Wallet` into a session type, parameterised
over its state which can be either `Locked` or `Unlocked`.
The default state is `Locked` in the case that the parameter is …
=> Distinguish between a `Wallet`'s `Locked` and `Unlocked` states

packages/fuels-test-helpers/src/node.rs
closes:https://github.com/FuelLabs/fuels-rs/issues/489
In https://github.com/FuelLabs/fuels-rs/pull/527 we refactored how the `Config` was used. To add new flags, we just have to extend it. For example, in this RP I added `vm_backtrace`
```rust
#[derive(Clone, Copy, Debug)]
pub struct Config {
pub addr: SocketAddr,
pub utxo_validation: bool,
pub predicates: bool,
pub manual_blocks_enabled: bool,
pub vm_backtrace: bool,
pub silent: bool,
}
impl Config {
pub fn local_node() -> Self {
Self {
addr: SocketAddr::new(Ipv4Addr::new(127, 0, 0, 1).into(), 0),
utxo_validation: false,
predicates: false,
manual_blocks_enabled: false,
vm_backtrace: false,
silent: true,
}
}
}
```
and later we can use this flag when starting the node:
```rust
if config.vm_backtrace {
args.push("--vm-backtrace");
}
``` …
=> feat: add vm-backtrace flag for local node

examples/providers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-test-helpers/src/script.rs, packages/fuels/tests/harness.rs
This changes from creating the `FuelClient` using `FuelClient::from(socket)` to `FuelClient::new(url)`.
The reason is that `from(socket)` was forcing it to be `http` only, and not `https`. `FuelClient::new(url)` takes an arbitrary URL as a string, which fixes this.
=> fix!: update connect method

packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/constants.rs, packages/fuels-core/src/lib.rs, packages/fuels-types/src/lib.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/options/Forc.toml, packages/fuels/tests/test_projects/options/src/main.sw, packages/fuels/tests/test_projects/results/Forc.toml, packages/fuels/tests/test_projects/results/src/main.sw
Closes: https://github.com/FuelLabs/fuels-rs/issues/421, https://github.com/FuelLabs/fuels-rs/issues/420, https://github.com/FuelLabs/fuels-rs/issues/415
This PR adds support for native rust `Options` and `Results` inside the SDK. We can now work with Sway contracts like:
```rust
struct TestStruct {
option: Option<Address>
}
enum TestEnum {
EnumOption: Option<Address>
}
abi MyContract {
fn get_some_u64() -> Option<u64>;
fn get_some_address() -> Option<Address>;
fn get_some_struct() -> Option<TestStruct>;
fn get_some_enum() -> Option<TestEnum>;
fn get_some_tuple() -> Option<(TestStruct, TestEnum)>;
fn get_none() -> Option<Address>;
fn input_primitive(s: Option<u64>) -> bool;
fn input_struct(s: Option<TestStruct>) -> bool;
fn input_enum(e: Option<TestEnum>) -> bool;
fn input_none(none: …
```
=> feat: add options and results support

docs/src/types/bytes32.md, docs/src/wallets/checking-balances-and-coins.md, examples/types/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels/tests/harness.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/584
- Added an example how to get a specific asset balance when using `wallet.get_balances()`.
- Refactored the `get_balance()` test and added `format!("{:#x}", asset_id)`.
- Update the Bytes32 documentation and show how we can get the hex string.
=> docs: update wallet get balance and types docs

docs/src/calling-contracts/calls-with-different-wallets.md, docs/src/contracts/the-setup-contract-test-macro.md, docs/src/cookbook/deposit-and-withdraw.md, examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, packages/fuels-abigen-macro/src/lib.rs, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels/tests/harness.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/515
- removed the `Builder` pattern from abigen
- added a new struct that holds the contract methods which is built by the `contract instance`
Now the workflow looks like this:
```rust
abigen!(
SimpleContract,
"packages/fuels/tests/takes_ints_returns_bool-abi.json",
);
let wallet = launch_provider_and_get_wallet().await;
// `SimpleContract` is the name of the contract
let contract_instance = SimpleContract::new(null_contract_id(), wallet);
let call_handler = contract_instance.methods().takes_ints_returns_bool(42);
```
In the tests where we have multiple contract calls, I have saved the methods in a new variable and called the methods directly. For example:
```rust
let contract_methods = SimpleContract::new(null_contract_id(), …
```
=> refactor!: add methods() to contract abigen

packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/lib.rs, packages/fuels-core/src/types/native.rs, packages/fuels-core/src/utils.rs, packages/fuels-types/src/lib.rs, packages/fuels/src/lib.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/identity/Forc.toml, packages/fuels/tests/test_projects/identity/src/main.sw
Using `Identity` in two deployed contracts would result in naming collision as both contract would make their own `Identity` enum. 
This PR fixes that by treating `Identity` as a native type.
- Updated abigen to use native `Identity`
- Added test for different `Identity` use-cases
=> feat: add Identity as native type

packages/fuels-contract/src/contract.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/foo_caller_contract/src/main.sw
Closes #609
We now make sure that the parsed `Return` receipt has an id field that matches the calling contracts `ContractId`.
=> fix: receipt parsing

packages/fuels-test-helpers/src/script.rs
I added a new `Option<Provider>` parameter to the `run_compiled_script`.
=> feat!: add `Option<Provider>` as parameter in run_compiled_script

.github/workflows/ci.yml, docs/src/calling-contracts/variable-outputs.md, examples/contracts/src/lib.rs, packages/fuels/tests/test_projects/liquidity_pool/src/main.sw, packages/fuels/tests/test_projects/token_ops/src/main.sw
`forc` `0.25` changed `transfer_to_output` (the Sway function) to `transfer_to_address`. This PR makes this change in our test contracts and documentation.
=> Fix: change transfer_to_output to transfer_to_address

examples/contracts/src/lib.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/logged_types/src/main.sw
Closes #603
Logging types with generics seems to work just fine, no further changes to the implementation were needed.
This PR just adds a new test case that calls `logs_with_type` on  generics with up to 3 levels of nesting.  It also extends the `fetch_logs` test with a generic type.
=> Test logging generics

.github/workflows/ci.yml, scripts/build-test-projects/src/lib.rs
Release `0.26` of `forc` removed the need for the `--generate-logged-types` flag on `forc build` commands.
=> ci: update `forc` version in CI

docs/src/types/bits256.md, packages/fuels-core/src/types/bits_256.rs
Small ergonomics improvement. 
Enables the user to do `let bits256 = Bits256::from_hex_str(hex_str)?;` to get a `Bits256` from their hex strings instead of having to do some more manual conversions.
=> feat: create `Bits256` from hex string

scripts/check-docs/src/lib.rs, scripts/check-docs/src/main.rs, scripts/check-docs/tests/harness.rs, scripts/check-docs/tests/test_data/test_include_data.md
closes: https://github.com/FuelLabs/fuels-rs/issues/638
Previously, the `regex` used to match `include` statements would skip includes that did not have an `anchor`. I have updated the regex and now the anchor is optional. Previously the program would stop if the `path` in the include statement is not correct, now we partition the result and show the path errors the same way as the other errors.
=> fix(check-docs): check whole file includes

docs/src/types/vectors.md
Part of the changed sentence isn't correct because it was written when returning vectors was possible.
=> docs: implication that returning vectors is a thing.

packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/node.rs
Seems like `fuel-core` doesn't take the `--predicates` flag anymore. So we're removing it from the SDK as well.
=> fix: remove predicates config flag

examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, examples/predicates/src/lib.rs, examples/providers/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-signers/src/lib.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/node.rs, packages/fuels-test-helpers/src/script.rs, packages/fuels-test-helpers/src/signers.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/providers.rs, packages/fuels/tests/wallets.rs
Enables passing a `ChainConfig` parameter to all test helpers related to node setup.
=> feat!: Accept chain config as argument for node setup test helpers

.github/workflows/ci.yml, packages/fuels-contract/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels/Cargo.toml
Update fuels-rs to the latest fuel-core v0.14. This release was necessary to unblock the bridging team as fuel-core was incorrectly using datetime strings instead of tai64 when representing time. No breaking changes to the VM or forc like fuel-core v0.13, so this is a very lightweight update.
=> fuel-core v0.14 tai64 timestamp support

docs/src/providers/short-lived.md, examples/contracts/Cargo.toml, examples/cookbook/Cargo.toml, examples/debugging/Cargo.toml, examples/predicates/Cargo.toml, examples/providers/Cargo.toml, examples/rust_bindings/Cargo.toml, examples/types/Cargo.toml, examples/wallets/Cargo.toml, packages/fuels-abigen-macro/Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, tools/fuels-abi-cli/Cargo.toml
Make a breaking version bump of fuels-rs in support of upgrading to fuel-core v0.14 to unblock bridge testing.
=> bump to v0.30.0 to release breaking fuel-core changes

docs/src/calling-contracts/logs.md
Simple doc update to remove the `--generate-logged-types` flag that is not needed anymore.
=> Remove note on `--generate-logged-types` in the Book

docs/src/api/contracts.md, docs/src/api/providers.md, docs/src/api/wallets.md, docs/src/getting-started/contracts.md, docs/src/workspaces/fuels-abi-cli.md, docs/src/workspaces/fuels-abigen-macro.md, docs/src/workspaces/index.md
This PR replaces `deploy_with_salt` with `deploy_with_parameters` in the docs. This was done by @MujkicA already in PR: https://github.com/FuelLabs/fuels-rs/pull/441 but is was probably missed when we did the big book update. 
In addition, I removed unused `.md` files from the docs.
=> chore: update `deploy_with_parameters` in docs

packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/contract_calls_utils.rs, packages/fuels-contract/src/execution_script.rs, packages/fuels-contract/src/script_calls.rs, packages/fuels-core/src/abi_encoder.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-types/src/lib.rs
> **Note** that this PR targets #620 (`iqdecay/feat-script-main-args`), as it is a byproduct of my review of #620.
- properly linkify some intra-doc links to Rust items 
- fix some improperly formatted links (e.g. bare URLs)
Tested with `cargo doc --document-private-items -p fuels-{contract,core}`.
=> docs(fuels-{contract,core}): minor updates

.github/workflows/ci.yml, examples/contracts/src/lib.rs
This PR updates the FORC_VERSION and RUST_VERSION constants in CI, and updates the expected test gas values accordingly.
=> ci: update `forc` and `rustc` version in CI

packages/fuels-core/src/code_gen/custom_types.rs, packages/fuels-core/src/code_gen/custom_types/enum_gen.rs, packages/fuels-core/src/code_gen/custom_types/utils.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels/tests/types.rs, packages/fuels/tests/types/complex_types_contract/src/main.sw
Structs can now be empty.
- Updated `code_gen` unit tests
- Added integration test
=> fix: support empty structs

.github/workflows/ci.yml, examples/contracts/src/lib.rs
Update to latest fuel-core v0.15.1 - fixes CI
In local testing I thought there was a problem with estimated gas costs, but it seems using the latest fuel-core binary was all that was needed to resolve the CI issues.
=> Update to fuel-core v0.15.1

packages/fuels-contract/src/contract.rs, packages/fuels-contract/src/script_calls.rs
We should not delete receipts when decoding the output from a contract call.
=> fix: do not modify receipts

.github/workflows/ci.yml
The `--no-verify` flag skips the sorting step of the github action we use to publish our crates. This might be causing some publishing issues right now. I'm removing it to experiment whether or not this fixes the publishing issue.
=> Remove --no-verify flag

docs/src/README.md, docs/src/providers/external-node.md, examples/providers/src/lib.rs, packages/fuels/tests/providers.rs
Update the `Connecting to the Testnet or an external node` section to refer to beta-2 instead of beta-1
closes #773
=> docs: update node-beta-1 to node-beta-2

.github/workflows/ci.yml, Cargo.toml, packages/fuels-core/src/offsets.rs, packages/fuels-programs/src/call_utils.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-types/src/message.rs
This updates all crates for the `fuel-asm` refactor introduced here: FuelLabs/fuel-vm#283. You can learn more about the change at this PR. The aim is to propagate this last API-breaking update through fuels-rs and sway before beta-3.
The associated fuel-core PR can be found here: FuelLabs/fuel-core#973.
Once the refactor lands upstream and the [patch] table is removed in this PR, this unblocks the associated sway update PR here: FuelLabs/sway#4004.
=> Update for `fuel-asm` refactor. Updates for fuel-core 0.17, fuel-vm 0.26.

.github/workflows/ci.yml, packages/fuels-core/src/constants.rs, packages/fuels-programs/src/constants.rs, packages/fuels-programs/src/contract.rs, packages/fuels-programs/src/lib.rs, packages/fuels-programs/src/logs.rs, packages/fuels-programs/src/script_calls.rs, packages/fuels/tests/contracts/asserts/Forc.toml, packages/fuels/tests/contracts/asserts/src/main.sw, packages/fuels/tests/logs.rs, packages/fuels/tests/scripts/script_asserts/Forc.toml, packages/fuels/tests/scripts/script_asserts/src/main.sw
closes: https://github.com/FuelLabs/fuels-rs/issues/812
This PR adds appropriate error messages to all `revert` transactions based on the IDs in  [error_signals.sw](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/error_signals.sw)
=> feat: support all revert signals

packages/fuels-test-helpers/src/node.rs, packages/fuels/tests/providers.rs
closes: #842 
Fuel-core probably uses HOME for the database path, so clearing all environment variables would cause problems for that use case. 
But since we use the in memory database, everything works even without the environment.
=> fix: clear environment before running fuel-core binary

.github/workflows/ci.yml, packages/fuels-signers/src/provider.rs, packages/fuels-types/src/transaction.rs
closes: #851
Passing `--workspace` will make cargo test each package individually. It is not exactly the same effect as going into the package and running `cargo test` due to workspace-wide feature unification happening before the test.
This is as close as we can get without bumping our CI times (probably) significantly by running `cargo test` for each package and then for the workspace as a whole.
=> fix: ci individual package testing

packages/fuels-core/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-signers/Cargo.toml
If you run 
```bash
CARGO_LOG=debug cargo update  
```
On a simple project that has `fuels = "0.37.0"` as a dep, among a bunch of other logs you'll see the following:
```
[2023-02-23T15:38:57Z INFO  cargo::sources::registry::index] failed to parse "fu/el/fuels-programs" registry package: feature `std` includes `fuels-test-helpers/std`, but `fuels-test-helpers` is not a dependency
[2023-02-23T15:38:57Z DEBUG cargo::core::registry] load/precise  registry `crates-io`
[2023-02-23T15:38:57Z DEBUG cargo::sources::registry::index] cache missing for "fu/el/fuels-signers" error: No such file or directory (os error 2)
[2023-02-23T15:38:57Z DEBUG cargo::sources::registry::index] slow path for "fu/el/fuels-signers"
[2023-02-23T15:38:57Z INFO  cargo::sources::registry::index] failed to parse …
```
=> fix: latest release cannot be used by cargo

.github/workflows/gh-pages.yml
Makes rust docs navigable from `rust.fuel.network`
=> Add cname for gh-pages

packages/fuels-code-gen/src/program_bindings/abigen.rs, packages/fuels-code-gen/src/program_bindings/custom_types.rs, packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs, packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs, packages/fuels/Cargo.toml, packages/fuels/src/lib.rs, packages/wasm-tests/Cargo.toml, packages/wasm-tests/src/lib.rs
closes: #912 
Read the issue for context. Only implementation notes to follow.
* `Abigen` code will now refer to types through the `fuels` package since it is now wasm compatible. @deekerno @ra0x3 the indexer should now just include `fuels` as a dependency taking care to disable the default features (since `std` is the default). You can access `fuels_core` stuff through `fuels::core`; `fuels_types` through `fuels::types`; `fuels_macros` through `fuels::macros`. 
The hotfix is still in place -- mostly to make the Abigen code-writing experience more enjoyable. If we remove it completely then we'd have to do a `no_std` check whenever we use a Vec, `format!`, `String` etc. 
This way we always write `::std::vec::Vec` and leave the rest to the (now smaller) wasm hotfix.
As we become more wasm …
=> refactor!: `fuels` wasm-offending packages/reexports hidden behind `std` flag

Cargo.toml, packages/fuels-accounts/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml
closes: #918 
From [the cargo book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html):
> Other than optional and features, inherited dependencies cannot use any other dependency key (such as version or default-features).
We've been inheriting workspace deps and then trying to disable default features. Cargo doesn't support this. If a dep has default features enabled when defined at the workspace level, those features are there to stay. You can only add more to them via `features` or make the dep itself optional in the place you're using it via `optional=true`.
The check for this still hasn't landed in cargo stable. I opted not to add a CI step to build `fuels-rs` with the nightly toolchain to check for regressions in this regard.
Functionally nothing has changed. The …
=> chore: default-features warnings on cargo nightly

docs/src/contracts/configurable-constants.md, docs/src/getting-started/predicates.md, docs/src/getting-started/running-scripts.md, docs/src/testing/the-setup-program-test-macro.md, examples/predicates/src/lib.rs, packages/fuels-accounts/src/predicate.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs, packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs, packages/fuels-core/src/lib.rs, packages/fuels-programs/src/contract.rs, packages/fuels-programs/src/lib.rs, packages/fuels/Forc.toml, packages/fuels/src/lib.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/predicates/predicate_configurables/Forc.toml, packages/fuels/tests/predicates/predicate_configurables/src/main.sw, packages/fuels/tests/types_predicates.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/931
Adds configurables for predicates the same way we did for scripts. The `Predicate` struct now has a method called `with_configurables` that creates a new updated predicate. Here is an example:
```rust
abigen!(Predicate(
name = "MyPredicate",
abi = "packages/fuels/tests/predicates/predicate_configurables/out/debug/predicate_configurables-abi.json"
));
let new_struct = StructWithGeneric {
field_1: 32u8,
field_2: 64,
};
let new_enum = EnumWithGeneric::VariantTwo;
let configurables = MyPredicateConfigurables::new()
.set_STRUCT(new_struct.clone())
.set_ENUM(new_enum.clone());
let predicate_data = MyPredicateEncoder::encode_data(8u8, true, new_struct, new_enum);
let mut predicate: Predicate = Predicate::load_from( …
```
=> feat!: add predicate configurables

packages/fuels-accounts/src/predicate.rs
Exposes a getter for the code field in `Predicate`
=> Add predicate code getter

Cargo.toml, examples/abigen/Cargo.toml, examples/contracts/Cargo.toml, examples/cookbook/Cargo.toml, examples/debugging/Cargo.toml, examples/predicates/Cargo.toml, examples/providers/Cargo.toml, examples/rust_bindings/Cargo.toml, examples/types/Cargo.toml, examples/wallets/Cargo.toml, packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/wallet.rs, packages/fuels-code-gen/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-macros/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, packages/wasm-tests/Cargo.toml
In this PR, I moved all our package dependencies to the workspace `Cargo.toml` and bumped all* to their latest versions (*except for `syn` - I will handle `syn` in a new PR as it introduced a lot of breaking changes)
=> chore: reorganize and bump external dependencies

.github/workflows/ci.yml, ci_checks.sh, examples/contracts/src/lib.rs, packages/fuels/tests/bindings/sharing_types/shared_lib/src/lib.sw, packages/fuels/tests/bindings/type_paths/src/another_lib.sw, packages/fuels/tests/bindings/type_paths/src/contract_a_types.sw, packages/fuels/tests/bindings/type_paths/src/main.sw, packages/fuels/tests/contracts.rs, packages/fuels/tests/contracts/auth_testing_abi/src/main.sw, packages/fuels/tests/contracts/configurables/src/main.sw, packages/fuels/tests/contracts/contract_test/src/main.sw, packages/fuels/tests/contracts/lib_contract_abi/src/main.sw, packages/fuels/tests/contracts/library_test/src/main.sw, packages/fuels/tests/contracts/multiple_read_calls/src/main.sw, packages/fuels/tests/contracts/storage/src/main.sw, packages/fuels/tests/logs/contract_logs/src/main.sw, packages/fuels/tests/logs/contract_logs_abi/src/main.sw, packages/fuels/tests/types/contracts/call_empty_return/src/main.sw, packages/fuels/tests/types/contracts/complex_types_contract/src/main.sw, packages/fuels/tests/types/contracts/empty_arguments/src/main.sw, packages/fuels/tests/types/contracts/vector_output/src/main.sw, packages/fuels/tests/types/contracts/vectors/src/data_structures.sw, packages/fuels/tests/types/contracts/vectors/src/eq_impls.sw, packages/fuels/tests/types/contracts/vectors/src/main.sw, packages/fuels/tests/types/contracts/vectors/src/utils.sw, packages/fuels/tests/types/scripts/script_vectors/src/data_structures.sw, packages/fuels/tests/types/scripts/script_vectors/src/eq_impls.sw, packages/fuels/tests/types/scripts/script_vectors/src/main.sw, packages/fuels/tests/types/scripts/script_vectors/src/utils.sw
Bumping the sway to `0.38.0` and `fuel-core` to `0.17.11`. Updated contracts according to new breaching changes.
It is preparation for the `fuel-core 0.18.0`. I extracted it into a separate change not to mix breaking changes from the `fuel-core` with breaking changes from the `sway`.
=> chore: update `sway` to `0.38.0` and `fuel-core` to `0.17.11`

packages/fuels-types/src/lib.rs
We've recently lost our `fuels::tx::Output` reexport of the `fuel_tx::Output`, this PR introduces it back but under a less surprising location (`fuels::types::output::Output` to mimic the already existing `fuels::types::input::Input`)
Although I'm not a fan of the `output::Output` verbosity, I decided to leave it so that it doesn't surprise users. 
We should probably reexport the types under `fuels::types::{Input, Output}` rather than needlessly mention the internal mod structure.
=> bug: reexport lost fuels::tx::Output under fuels::types::output::Output

packages/fuels-programs/src/script_calls.rs, packages/fuels/tests/scripts.rs
=> feat: add gas estimation to script calls

Cargo.toml
cc @xgreenx 
We need to update our min `fuel-core` dependency to incorporate a vm bugfix
=> chore: set `fuel-core` to `0.18.2`

.github/workflows/ci.yml
Forgot to add doctests since nextest doesn't test them.
=> ci: add back doctest testing

Cargo.toml, packages/fuels/Cargo.toml
Should show the top-level `README.md` for `fuels` (`packages/fuels`) on [crates.io](https://crates.io/crates/fuels).
Not sure on how to test this besides merging and cutting a release to check crates.io.
Close #1025.
=> docs: show README.md for fuels on crates.io

packages/fuels-code-gen/src/program_bindings/resolved_type.rs, packages/fuels-core/src/codec/abi_decoder.rs, packages/fuels-core/src/codec/function_selector.rs
Realized some were missing while working on `String` support.
=> test: implement tests over `Bytes` type

packages/fuels-code-gen/src/program_bindings/resolved_type.rs, packages/fuels-core/src/codec/abi_decoder.rs, packages/fuels-core/src/codec/abi_encoder.rs, packages/fuels-core/src/codec/function_selector.rs, packages/fuels-core/src/traits/parameterize.rs, packages/fuels-core/src/traits/tokenizable.rs, packages/fuels-core/src/types.rs, packages/fuels-core/src/types/core/sized_ascii_string.rs, packages/fuels-core/src/types/param_types.rs, packages/fuels-programs/src/contract.rs
Add support for `str` in prevision for https://github.com/FuelLabs/sway/pull/4778
=> feat!: add support for string slices

examples/cookbook/src/lib.rs, packages/fuels-accounts/src/lib.rs, packages/fuels-code-gen/src/program_bindings/abigen.rs, packages/fuels-code-gen/src/program_bindings/abigen/abigen_target.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/utils.rs, packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs, packages/fuels-code-gen/src/program_bindings/abigen/logs.rs, packages/fuels-code-gen/src/program_bindings/custom_types.rs, packages/fuels-code-gen/src/program_bindings/custom_types/enums.rs, packages/fuels-code-gen/src/program_bindings/custom_types/structs.rs, packages/fuels-code-gen/src/program_bindings/custom_types/utils.rs, packages/fuels-code-gen/src/program_bindings/utils.rs, packages/fuels-code-gen/src/utils/source.rs, packages/fuels-core/src/types.rs, packages/fuels-core/src/types/wrappers/block.rs, packages/fuels-core/src/types/wrappers/chain_info.rs, packages/fuels-core/src/types/wrappers/message_proof.rs, packages/fuels-core/src/types/wrappers/transaction_response.rs, packages/fuels-macros/src/derive/utils.rs, packages/fuels-test-helpers/src/node.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/providers.rs, packages/fuels/tests/wallets.rs
closes: #1060 
The solution (until Rust has an official way of doing it) is to call `include_bytes` inside your macro. This is detected by the compiler and it will watch the path for changes. 
I've assigned it to a `const _: &[u8] = include_bytes!(...)` and it seems it gets optimized away. 
Couldn't find a trace of the JSON file in the resulting executable (even under debug build). 
So we might have gotten away with a no-downsides hack.
Tested via a separate e2e suite. Didn't include it in the PR since it would require compiling the whole SDK twice during testing.
=> feat: macro recompile trigger

docs/src/calling-contracts/low-level-calls.md, packages/fuels/tests/contracts/contract_test/src/main.sw
closes: https://github.com/FuelLabs/fuels-rs/issues/1071
=> docs: fix `low_level_call` anchor

packages/fuels-programs/src/script_calls.rs
After doing some script debugging, I have seen that we did not have a way to extract the `tx` from a `ScriptCallHandler` as we do with the `ContractCallHandler`.
=> feat: add `build_tx` to `ScriptCallHandler`

.github/workflows/ci.yml, Cargo.toml
Bump rust to `1.71.1` and update our dependencies.
=> chore: bump rust and deps versions

packages/fuels-core/src/types/core/sized_ascii_string.rs
- Really hoping this is the last SizedAsciiString update 🤞🏽
=> chore: derive Default for SizedAsciiString

docs/src/calling-contracts/multicalls.md, packages/fuels-programs/src/contract.rs, packages/fuels/tests/contracts.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1085
The `MultiContractCallHandler` can have one call with a heap return type but it must be placed on the last position.
=> fix: validate multi-calls wrt to heap types

Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-core/src/types/wrappers/block.rs, packages/fuels-core/src/types/wrappers/transaction_response.rs, packages/fuels/tests/providers.rs
Our CI is failing because a warning caused by deprecated functions.
=> chore: replace deprecated `chrono` functions

packages/fuels-code-gen/src/program_bindings/abigen/configurables.rs
close: https://github.com/FuelLabs/fuels-rs/issues/1101
The warnings generated when names of configurables have uppercase letters is now suppressed with `#[allow(non_snake_case)]`
=> chore: remove `non_snake_case` warning for configurables

.github/workflows/ci.yml, examples/contracts/src/lib.rs, packages/fuels-core/Cargo.toml, packages/fuels/tests/contracts/lib_contract_caller/src/main.sw, packages/fuels/tests/contracts/storage/src/main.sw, packages/fuels/tests/scripts/script_enum/src/main.sw, packages/fuels/tests/types/contracts/generics/src/main.sw, packages/fuels/tests/types/contracts/identity/src/main.sw, packages/fuels/tests/types/contracts/options/src/main.sw, packages/fuels/tests/types/contracts/results/src/main.sw, packages/fuels/tests/types/contracts/tuples/src/main.sw, packages/fuels/tests/types/predicates/enums/src/main.sw, packages/fuels/tests/types/predicates/predicate_tuples/src/main.sw, packages/fuels/tests/types/predicates/predicate_vectors/src/main.sw, packages/fuels/tests/types/scripts/script_vectors/src/main.sw
I have updated our test projects to work with `forc: 0.45.0` and removed all warnings.
I have also added the ` --error-on-warnings` flag to `forc build` - let me know what you think!
I changed the order of the `increment_from_contract_then_mint` function because of a compiler warning stating that we should first change the balance and then call external contracts.
=> chore: bump `forc` to `0.45.0`

docs/src/SUMMARY.md, docs/src/deploying/storage-slots.md, examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, packages/fuels-code-gen/src/program_bindings/abigen.rs, packages/fuels-core/src/types/bech32.rs, packages/fuels-core/src/types/core/sized_ascii_string.rs, packages/fuels-core/src/types/param_types.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-macros/src/setup_program_test/code_gen.rs, packages/fuels-programs/Cargo.toml, packages/fuels-programs/src/call_utils.rs, packages/fuels-programs/src/contract.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/storage.rs
closes: #1117 #1118 
Storage slots are now loaded automatically by default (an opt-out exists). 
If the `StorageConfiguration` indicates that autoload should take place, `Contract::load_from` will try and discover the storage slots file in the same directory as the contract binary to be loaded.
If it is for some reason missing this constitutes an error. The user will be guided to either provide the file or disable autoloading.
Any additional storage slots configured in `StorageConfiguration` act as an override taking precedence over what was loaded from the storage slots file. 
Enabling the autoloading uncovered a bug where we didn't account for storage slots when calculating the heap data offset for predicates.
The storage configuration interface changed
Autoloading by default might …
=> feat!: autoload storage slots

examples/contracts/src/lib.rs, packages/fuels-programs/src/call_utils.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/providers.rs
Use `REG_CGAS` register if no `gas_forwarded` was not set for a specific call.
=> feat: use `REG_CGAS` as default forwarded gas

.github/workflows/ci.yml, packages/fuels-accounts/Cargo.toml, packages/fuels-code-gen/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-macros/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-test-helpers/Cargo.toml
No relevant issue - just tech debt.
Removes dependencies unused by our crates, and adds a step to `ci.yml` to report them in the future.
This is accomplished with [`cargo-machete`](https://github.com/bnjbvr/cargo-machete), which reported only a single false positive - a crate called `Inflector` (titlecase), but used in code as `inflector` (lowercase); I added a corresponding exception.
=> chore(deps): remove unused deps, add corresponding CI check

packages/fuels/tests/providers.rs
Should be reverted once https://github.com/FuelLabs/fuel-core/issues/1384 is merged - tracked in https://github.com/FuelLabs/fuels-rs/issues/1144.
=> fix(ci): ignore testnet_hello_world test

packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/codec/logs.rs, packages/fuels-programs/src/contract.rs, packages/fuels-programs/src/script_calls.rs, packages/fuels/tests/providers.rs
While working on an other issue, I have seen that we have some duplicated code for revert error mapping. I have refactored the code a bit so that we can remove the `map_revert_error` function and use the logic inside `TxStatus`
=> refactor: use `TxStatus` to map revert errors

packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/types/errors.rs, packages/fuels-core/src/types/tx_status.rs, packages/fuels-programs/src/contract.rs
close: https://github.com/FuelLabs/fuels-rs/issues/1141
This PR adds a check of the tx status when deploying contracts.
I have refactored the code a bit and added a new error variant `SqueezedOutTransactionError`. I am not sure if this should be an error. What do you think @FuelLabs/sdk-rust ?
=> feat: check deploy tx status

Cargo.toml, packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/wallet.rs, packages/fuels-core/Cargo.toml, packages/fuels-core/src/types/transaction_builders.rs
Close https://github.com/FuelLabs/fuels-rs/issues/1157.
These are all the relevant usages of `SecretKey` @segfault-magnet proposed - I found no more usages.
=> feat: securely zero out `SecretKey`s from memory

packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs, packages/fuels-core/src/codec/abi_encoder.rs, packages/fuels-core/src/types/param_types.rs, packages/fuels-programs/src/call_utils.rs, packages/fuels/Forc.toml, packages/fuels/tests/types/contracts/heap_type_in_enums/src/main.sw, packages/fuels/tests/types/contracts/string_slice/Forc.toml, packages/fuels/tests/types/contracts/string_slice/src/main.sw, packages/fuels/tests/types_contracts.rs
This PR adds support for `str` returned from contract calls (either directly, or inside `enums`)
Full support will be added once `sway` is ready. Issue to track: https://github.com/FuelLabs/fuels-rs/issues/1158
=> feat: return `str` from contracts

README.md, docs/src/abigen/the-json-abi-file.md, docs/src/deploying/index.md, docs/src/getting-started.md
CI  is failing because of broken links.
cc @cold-briu
=> fix: broken docs links

.github/workflows/ci.yml, Cargo.toml, packages/fuels-code-gen/src/program_bindings/utils.rs, packages/fuels-core/Cargo.toml, packages/wasm-tests/Cargo.toml, scripts/check-docs/Cargo.toml, scripts/versions-replacer/Cargo.toml
Bump `dasel` and dependencies versions. Fixed a `clippy` nightly warning that we should not have functions after a test mod.
=> chore: bump `dasel` and deps versions

packages/fuels/tests/types/contracts/std_lib_string/src/main.sw, packages/fuels/tests/types/predicates/predicate_std_lib_string/src/main.sw, packages/fuels/tests/types/scripts/script_std_lib_string/src/main.sw
closes: https://github.com/FuelLabs/fuels-rs/issues/1064
`Sway` has got a new `Eq` implementation for `String` so we can use it it directly. https://github.com/FuelLabs/sway/pull/5055
=> feat: use `String` directly in `assert_eq`

packages/fuels-programs/src/call_utils.rs, packages/fuels/tests/contracts.rs
In [1122](https://github.com/FuelLabs/fuels-rs/pull/1122) I introduced a bug where contract arguments are not put at the right location in the script data. We did not catch this because we did not have a test that has arguments and uses `gas_forwarded`. I have fixed the issue and added a test to cover this use-case.
=> fix: encode contract arguments with `gas_forwarded`

packages/fuels/tests/providers.rs
Reverts FuelLabs/fuels-rs#1143. Closes #1144.
=> Revert "fix(ci): ignore testnet_hello_world test"

packages/fuels-test-helpers/src/fuel_bin_service.rs
#1132
Moves the server health check to take place after the thread for collecting command output is spawned.
It seems like the the previous spot at which we did the health check was hiding a bug. The `NamedTmpFile` get's dropped with no guarantee that it was read during node startup. The health check bought just enough time for it it to succeed. It
Thanks to @segfault-magnet for explaining what the cause was and suggesting a quick fix.
=> Move health check after error collection

packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs, packages/wasm-tests/src/lib.rs
As the `Predicates` code is wasm compatible ([1667](https://github.com/FuelLabs/fuels-rs/pull/1167)), we can also expose the structs for encoding and configurables from abigen.
- I have updated the predicate wasm test to include the abigen code.
=> feat: generate full predicate abigen code in wasm

docs/src/calling-contracts/tx-policies.md, packages/fuels-accounts/src/account.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-core/src/types/wrappers/transaction.rs, packages/fuels-core/src/utils.rs, packages/fuels-core/src/utils/constants.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/logs.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/providers.rs, packages/fuels/tests/types_contracts.rs, packages/fuels/tests/wallets.rs
This PR improves the usage of `TxPolicies` and fixes some of the issues that remained after their were introduced.
BREAKING CHANGE:
- `ScriptTransactionBuilder` and `CreateTransactionBuilder` do not have `with_maturity` and `with_gas_price`, (`with_gas_limit`). They are set through the `with_tx_policies` method.
- `Maturity` is not set to `0` by default - instead we use an `Option<u64>` and `None` if it was not set. This saves bytes as it is not serialized if `None`
- `WitnessLimit` is set to the size of all witnesses in the builder. If the user uses `append_witnesses` after finalizing the transaction a new error will be returned that helps the user set the witness limit manually.
=> feat!: improve transaction builders wrt `TxPolicies`

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_versions.rs, packages/fuels-core/src/types/wrappers/chain_info.rs
BREAKING CHANGE:
-  removed the `peer_count` field from `ChainInfo`
=> chore!: bump `fuel-core` to `0.22`

packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/retryable_client.rs, packages/fuels-core/src/types/tx_status.rs
`fuel-core` now provides `receipts` inside the `TransactionStatus`.
=> refactor: use receipts from `TransactionStatus`

packages/fuels-accounts/src/account.rs
Resolves the issue https://github.com/FuelLabs/fuels-rs/issues/1239
=> fix: use only base asset amount when calculating fee

docs/src/types/address.md, docs/src/types/bytes32.md
Came across two dead links while reading the docs.
{{versions.fuel-types}} doesn't work anymore and leads to this : 
"latest" works fine.
Hope I can help a bit, have a nice week-end
=> chore: fixing broken links

.github/workflows/ci.yml
Due to recent changes in the action used to publish our crates, cyclic dependencies were being poorly handled, resulting in our CI failing to publish the `0.55` version. This PR changes the action, replacing the original one with the one forked and maintained by @xgreenx (thanks, green!).
=> Change publish action

packages/fuels-programs/src/contract.rs, packages/fuels-programs/src/script_calls.rs
The `response` method from `ScriptCallHandler`, `ContractCallHandler` and `MultiContractCallHandler` was unreachable because of:
```rust
let tx_id = self.cached_tx_id.expect("Cached tx_id is missing");
```
Which means that if there is no cached `tx_id` this method will panic. The only way to get a `tx_id` is by calling `call`, `simulate` or `submit` and these methods return other types that handle the response.
Even though this method was never used, I will mark the PR as breaking as the method was `pub`.
BREAKING CHANGE: remove `response` method from `ScriptCallHandler`, `ContractCallHandler` and `MultiContractCallHandler`.
=> chore!: remove unused `response` method

examples/contracts/src/lib.rs, examples/types/src/lib.rs, packages/fuels-core/src/types.rs, packages/fuels/src/lib.rs, packages/fuels/tests/storage.rs
`AssetId` was exported two times. Once through `fuels::tx::AssetId` and once through `fuels::types::AssetId`.
In addition, we were exposing `fuel_types` through `fuel_tx` and `fuels::tx`.
This PR exposes all `fuel_types` directly through `fuels::types` and leaves `fuel_tx` relevant exports to `fuels::tx`.
BREAKING CHANGE: 
- `Bytes32` and `Salt` are accessed through `fuels::types`
- `UtxoId` and `TxPointer` are accessed through `fuels::tx`
=> chore: refactor `fuel_types` imports

packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/retryable_client.rs, packages/fuels-accounts/src/provider/supported_versions.rs, packages/fuels/tests/providers.rs
Version incompatibility is now a soft error appended to every provider error.
=> feat: version incompatibility is now a soft warning

.gitattributes
Github recognizes Sway files and does not need them to be marked as Rust anymore.
=> chore: remove syntax highlighting of Sway files as Rust

packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/provider.rs, packages/fuels-core/Cargo.toml, packages/fuels-core/src/types/tx_status.rs, packages/fuels/tests/logs.rs
=> bug: fix revert id

packages/fuels-accounts/src/wallet.rs
This PR makes a small addition to the in-line docs of `new_from_mnemonic_phrase_with_path ` to clarify that it is not restricted to BIP32 derivation paths only.
Closes #1369
=> chore: update `wallet.rs` in-line BIP doc

Cargo.toml, e2e/sway/contracts/contract_test/src/main.sw, e2e/sway/scripts/basic_script/src/main.sw, packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/function_generator.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/predicate.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1335
Adds ABI doc strings to contract methods and script's main function.
=> feat: use doc strings from the `abi` in `abigen`

packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs, packages/fuels-programs/src/contract.rs, packages/fuels-programs/src/script_calls.rs, packages/fuels-programs/src/submit_response.rs
Removed `provider` from `ScriptCallHandler`. The `provider` can be accessed from the `account` the same way we do in `ContractCallHandlers`. 
Another benefit is that we will not panic when initializing a new script instance if the provider is not set up.
=> refactor: remove `provider` from `ScriptCallHandler`

Cargo.toml, e2e/Cargo.toml, e2e/build.rs
closes: #1397
The `build.rs` will now check:
* Whether the `version.rs` is updated
* Whether the executor is downloaded
* If downloaded, is it the same version as can be found in our `version.rs`
* cleanup if any step fails
=> bug: e2e build script

e2e/tests/providers.rs
The test just submitted transactions without awaiting their commitment, causing CI to sometimes complain about transactions being processed out of place... :facepalm: 
related: #1382
=> bug: await tx committal

packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/types/transaction_builders.rs
=> feat: use fallback predicate estimation in `set_max_fee_policy`

e2e/tests/contracts.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-programs/src/calls/traits/transaction_tuner.rs, packages/fuels-programs/src/calls/utils.rs, packages/fuels-programs/src/contract.rs
closes: #1457 
We now add a 5% tolerance to max fee estimation just like we do for script gas estimation.
=> feat: add max fee estimation tolerance

README.md, docs/src/getting-started.md
Updating `forc build --path` usages in docs based on the update in #1374.
=> chore: update `forc build` path in docs

e2e/tests/contracts.rs, packages/fuels-accounts/src/accounts_utils.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/types/transaction_builders.rs
closes: #1463 
* `fee_checked_from_tx` is removed from all transaction builders. max fee can now be estimated using the new method `estimate_max_fee` which takes into account the max fee estimation tolerance set on the builders.
=> bug!: accounts now cover max fee increase due to tolerance

packages/fuels-core/src/codec.rs, packages/fuels-core/src/codec/abi_decoder/bounded_decoder.rs
closes: #1482 
The decoder didn't report the correct number of bytes read when decoding a string slice. 
- [] I have updated the documentation.
=> fix: string slice decoding

e2e/tests/contracts.rs, packages/fuels-programs/src/calls/call_handler.rs
=> fix: state read dry run sets gas price to 0

Cargo.toml, scripts/change-log/Cargo.toml, scripts/change-log/src/get_full_changelog.rs, scripts/change-log/src/get_latest_release.rs, scripts/change-log/src/main.rs
The crate references the workspace but it is not part of it. In order to run it via `cargo run --bin` (and to silence the cargo warnings) we need to make it part of the workspace like the other scripts.
=> chore: add change log script to the workspace

e2e/sway/types/contracts/generics/src/main.sw, e2e/tests/types_contracts.rs
Related: https://github.com/FuelLabs/sway/issues/5860
Adds the above mentioned case to our tests.
=> chore: extend types tests with array with generics

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
Updated `fuel-core` to `0.36.0`
=> chore: update `fuel-core` to `0.36.0`

e2e/tests/scripts.rs, packages/fuels-core/src/lib.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-core/src/utils/constants.rs, packages/fuels-programs/src/executable.rs
Loader and Regular executables now offer insight into the data section offset within.
Configurables can be shifted by a i64 offset.
Default estimation horizon bumped from 1 to 5.
=> feat: expose loader data offset + bump default gas horizon

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs, packages/fuels-test-helpers/src/service.rs
- Updated fuel-core to `0.38.0`
=> chore: bump fuel-core to 0.38.0

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs, packages/fuels-test-helpers/src/service.rs
updated `fuel-core` to `0.39.0`
=> update `fuel-core` to `0.39.0`

Cargo.toml, scripts/fuel-core-version/Cargo.toml, scripts/fuel-core-version/src/main.rs
- Closes: #1551 
Now we read from the `Cargo.toml` and use that for the CI check. More details in the issue.
=> bug: read cargo toml instead of running cargo metadata

Cargo.toml, e2e/tests/providers.rs, packages/fuels-accounts/src/coin_cache.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
Checks if any of the inputs is already cached before sending/submitting the tx.
=> feat: check if coin already in cache

packages/fuels-programs/src/calls/receipt_parser.rs
Made the `extract_contract_call_data` function public in the `ReceiptParser` struct to allow external access to the function.
This is required to construct low-level calls if you dont want to use `CallHandler` and instead want to manually deal with the low-level bytes (`Vec<u8>`) data.
=> feat: `extract_contract_call_data` function pub modifier

Cargo.toml, packages/fuels-test-helpers/Cargo.toml
Closes: #1556 
- froze async-graphql to `7.0.11` until the SDK MSRV moves to 1.81 needed for `7.0.12` onwards.
If you build the SDK with the `fuel-core-lib` feature *and* have a dep on `async-graphql` you'll only be able to use the version `7.0.11` until the SDK moves its MSRV to 1.81.
=> freeze gql version to 7.0.11 due to MSRV incompatibility of 7.0.12>=

packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/wallet.rs
- `WalletUnlocked` exposes `secret_key()` function under `test-helpers` feature-flag.
When testing, it is useful to retrieve the secret-key of a wallet (to be used in other functions) - especially in other repos.
This PR introduces the `secret_key()` function on the `WalletUnlocked` which is only enabled under the `test-helpers` feature flag.
=> `WalletUnlocked` function to expose `SecretKey` under `test-helpers` feature-flag

packages/fuels/Cargo.toml
- Closes: #1559 
Added a feature flag on `fuels` that will enable `test-helpers` on `fuels-accounts` when it itself is enabled.
=> chore: propagate `test-helpers` feature flag to `fuels-accounts` from `fuels`

Cargo.toml, e2e/tests/contracts.rs, e2e/tests/predicates.rs, e2e/tests/providers.rs, e2e/tests/wallets.rs, examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, examples/providers/src/lib.rs, packages/fuels-accounts/Cargo.toml, packages/fuels-accounts/src/account.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/cache.rs, packages/fuels-accounts/src/provider/retryable_client.rs, packages/fuels-core/src/types/dry_runner.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-core/src/types/transaction_builders/blob.rs, packages/fuels-core/src/types/transaction_builders/script_tx_estimator.rs, packages/fuels-programs/src/calls/call_handler.rs, packages/fuels-programs/src/calls/utils.rs, packages/fuels-programs/src/contract/regular.rs, packages/fuels-test-helpers/src/accounts.rs, packages/fuels-test-helpers/src/lib.rs
- Closes #1561 
- Made the `ConsensusParameters` cache expire-able in `Provider`
The `Provider` now evicts the cached `ConsensusParameters` after the preconfigured TTL (defaulted to 60s).
You can change the TTL by doing:
```rust
provider.set_cache_ttl(TtlConfig {
consensus_parameters: Duration::from_secs(5),
});
```
If you want to clear the cache immediately you can do so by:
```rust
provider.clear_cache().await;
```
The `consensus_parameters` method in `Provider` is now `async` and fallable:
```rust
pub async fn consensus_parameters(&self) -> Result<ConsensusParameters>
```
The following methods have been removed:
- `base_asset_id` -- now acquired by `provider.consensus_parameters().await?.base_asset_id()`
- `chain_id` -- now acquired by …
=> bug!: updating consensus parameters

packages/fuels-accounts/src/account.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/types/dry_runner.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-core/src/types/wrappers/transaction.rs
- `estimate_predicates` no longer returns an option
At one point we stopped estimating predicates locally due to not having blobs available to dry run the predicates with. We couldn't break the API at that point so we always returned `Some(tx)`. 
We now remove the `Option` from the API
`maybe_estimate_predicates` renamed to `estimate_predicates` and the return type changed from `Result<Option<Tx>>` to `Result<tx>`.
=> chore!: remove option return from predicate estimation

packages/fuels-accounts/src/provider.rs
Use pagination for `balances`, `contract_balances` and `messages` requests.
=> feat: use pagination in requests

packages/fuels-programs/src/contract/loader.rs
While working on the `total_fee` and `total_gas` PR I noticed that we rely on the error message to check if a blob is already included. Refactored the code to use the `blob_exist` endpoint.
=> feat: use `blob_exists` endpoint before uploading contract blob

.github/workflows/ci.yml, Cargo.toml, e2e/tests/contracts.rs, e2e/tests/types_predicates.rs, e2e/tests/wallets.rs, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs, packages/fuels-accounts/src/schema/schema.sdl, packages/fuels-test-helpers/Cargo.toml, packages/fuels-test-helpers/src/service.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1579 and https://github.com/FuelLabs/fuels-rs/issues/1580
Bump `fuel-core` to `0.41.3` and fix ignored tests.
=> fix: bump `fuel-core` to `0.41.3` and fix test

e2e/tests/contracts.rs, e2e/tests/scripts.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/types/dry_runner.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-programs/src/calls/traits/transaction_tuner.rs, packages/fuels-programs/src/calls/utils.rs, packages/fuels-programs/src/contract/loader.rs, packages/fuels-programs/src/contract/regular.rs, packages/fuels-programs/src/executable.rs, packages/fuels-programs/src/lib.rs
- Closes: #1589 
- added max fee estimation tolerance to `ScriptCallHandler`'s `convert_into_loader` to reduce the occurrence of invalid max fees.
`ScriptCallHandler::convert_into_loader` and `Executable::upload_blob` now use the default max fee estimation tolerance when building the blob tx. This should lessen the occurrence of invalid max fees due to using a different amount of coins than what we estimated with.
=> bug: script/predicate blob upload now uses the default max fee estimation tolerance

e2e/tests/predicates.rs, e2e/tests/wallets.rs, packages/fuels-accounts/src/accounts_utils.rs
`adjust_for_fee` should not count messages with data as spendable inputs.
=> fix: message with data exluded in `adjust_for_fee`

e2e/tests/predicates.rs, e2e/tests/wallets.rs, packages/fuels-accounts/src/accounts_utils.rs
Pure cherry pick, no additional changes. 
- Backported a fix that doesn't take into account messages with data as assets that can cover gas fees.
=> bug: backport msg w data fee adjustment fix

packages/fuels-core/src/types/errors.rs
Adds `context` and `with_context` to `Result` - based on `anyhows`'s `Context` trait.
=> feat: add context to `Result`

packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/cache.rs, packages/fuels-accounts/src/provider/retryable_client.rs
Closes: #1615 
- added a fallback for querying balances when indexation is not supported
=> bug: fallback to single large request if no indexation available

packages/fuels-accounts/src/signers/private_key.rs
When viewing the [docs hub example](https://docs.fuel.network/docs/fuels-rs/wallets/signing/#signing) on how to recover a public key, the variable name provided is `recovered_address`. This is misleading and leads to confusion as the recovered type is a `PublicKey` https://github.com/FuelLabs/fuel-vm/blob/09c500838b734603970c62d414e0e95825f44773/fuel-crypto/src/secp256/signature.rs#L140C56-L140C65. This has been updated to a more appropriate name.
=> chore: update public key recovery example in docs

packages/fuels-core/src/types/wrappers/coin.rs, packages/fuels-programs/src/calls/utils.rs, packages/fuels-test-helpers/src/lib.rs
closing: https://github.com/FuelLabs/fuels-rs/issues/1663
removed `CoinStatus` and `created_at` from `Coin`
```rust
//old
pub struct Coin {
pub amount: u64,
pub block_created: u32,
pub asset_id: AssetId,
pub utxo_id: UtxoId,
pub owner: Bech32Address,
pub status: CoinStatus,
}
```
```rust
//new
pub struct Coin {
pub amount: u64,
pub asset_id: AssetId,
pub utxo_id: UtxoId,
pub owner: Bech32Address,
}
```
=> chore!: remove `CoinStatus` and `block_created` from `Coin`

packages/fuels-accounts/src/provider.rs, packages/fuels-core/src/codec/logs.rs
This pull request introduces a new lazy log decoding feature to the `fuels-core` log codec, enabling more efficient and flexible extraction and decoding of logs from receipts. The main changes focus on adding a lazy decoding API, supporting type-specific log extraction, and implementing the necessary traits and iterator logic.
* Added the `decode_logs_lazy` method to the `LogDecoder` struct, allowing users to obtain an iterator of lazy decoder functions for a specific log type from a single `Receipt`. This enables on-demand decoding and can improve performance for large log sets.
* Introduced the `ExtractLogIdLazy` trait, which provides the `extract_matching_logs_lazy` method for iterators over receipts. This method filters receipts by target log IDs and returns an iterator of lazy …
=> chore(log_id): lazy data decode

Cargo.toml
looks like some documentation was already updated to use 0.75.0, its not on crates.io or gh releases though
=> chore(release): prepare for release 0.75.0
