.github/workflows/ci.yml
=> Add publish delay

fuels-abigen-macro/Cargo.toml, fuels-core/Cargo.toml, fuels-rs/Cargo.toml, fuels-rs/src/contract.rs, fuels-rs/src/script.rs, fuels-rs/tests/calls.rs, fuels-signers/Cargo.toml
Closes https://github.com/FuelLabs/fuels-rs/issues/34
=> Fix breaking changes introduced by new UtxoId

README.md
=> Update Rust badges to `fuels-contract`

fuels-abi-cli/Cargo.toml, fuels-abigen-macro/Cargo.toml, fuels-contract/Cargo.toml, fuels-core/Cargo.toml, fuels-signers/Cargo.toml
There shouldn't have been any breaking changes since v0.4.0 I think.
=> Bump to v0.4.1.

README.md, fuels-abigen-macro/README.md, fuels-abigen-macro/tests/test_projects/two-structs/tests/harness.rs
Some things I forgot during refactoring
=> docs: fix docs for new contract instantiation

fuels-abigen-macro/tests/harness.rs, fuels-contract/src/contract.rs
Before, forwarding a non-native asset ID wasn't having an effect -- the asset ID always ended up as being the native one. This PR fixes this. Now the `Call` registers the asset ID passed by the user:
```
CallResponse { value: 0, receipts: [Call { id: 0xeb41245813e928b57b2c57ee14b0dfa4073687d3c69792f8bc14beed6825ffae, 
to: 0xeb41245813e928b57b2c57ee14b0dfa4073687d3c69792f8bc14beed6825ffae, amount: 0, 
asset_id: 0xeb41245813e928b57b2c57ee14b0dfa4073687d3c69792f8bc14beed6825ffae, 
gas: 999967, a: 2830212025, b: 1, pc: 1712, is: 1712 }] }
```
However, as noted in one of the tests, the VM is complaining about the asset ID being forwarded not being found. This only happens when `amount > 0`. Not sure where the issue is located at, but doesn't seem to be SDK-related.
=> Support non-native asset forwarding

Cargo.lock, fuels-abi-cli/Cargo.toml, fuels-abigen-macro/Cargo.toml, fuels-contract/Cargo.toml, fuels-contract/src/contract.rs, fuels-core/Cargo.toml, fuels-signers/Cargo.toml
Bump various Fuel dependencies.
=> Bump fuel-core to v0.5.0

fuels-core/src/lib.rs
This PR implements the missing `Detokenize` trait for `Address`.
=> Implement Detokenize trait for Address

packages/fuels-abigen-macro/tests/test_projects/auth_testing_abi/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/auth_testing_contract/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/call_empty_return/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/contract_test/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/empty_arguments/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/large_return_data/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/library_test/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/multiple_read_calls/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/simple_script/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/token_ops/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/tuples/Forc.toml, packages/fuels-abigen-macro/tests/test_projects/two_structs/Forc.toml
=> ci: use implicit `sway-std-lib` dependency in tests projects

docs/src/getting-started/basics.md, packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-contract/src/contract.rs, packages/fuels-core/src/code_gen/abigen.rs, packages/fuels-core/src/code_gen/functions_gen.rs, packages/fuels-test-helpers/src/signers.rs
=> Contract deployment QoL

packages/fuels-core/src/lib.rs, packages/fuels/Cargo.toml, packages/fuels/src/lib.rs
Close #278. Might use some items in `prelude`.
=> Re-export fuel_tx in fuels

docs/src/getting-started/basics.md, packages/fuels-contract/src/contract.rs
=> Added `deploy_with_salt` function

docs/src/getting-started/setup.md
=> docs: update `fuels-*` version in the book

packages/fuels-abigen-macro/tests/harness.rs, packages/fuels-contract/src/contract.rs
Closes #282
Since we concluded that `load_sway_contract()` and `load_sway_contract_with_salt()` should still remain exposed to the user, I've added `deploy_loaded()` so that the output of those functions can be deployed. 
I thought about removing `deploy_with_salt()` since its functionality can be replicated with `load_sway_contract_with_salt()` + `deploy_loaded()` but it seems more user friendly to have a similar workflow for deploying with and without salt.
I've also added a small test `same_contract_different_ids` to cover the case when the exact same contract is being deployed twice.
=> Add deploy for loaded contract

packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs
I implemented 2 methods:
- get_transactions() in a Wallet.rs that returns wallet-related transactions 
- get_transactions() in a Provider.rs that returns all transactions
=> add get_transactions to Wallet and Provider

docs/theme/highlight.js
Add sh, console, and json. Ref: https://github.com/FuelLabs/sway/pull/1699
=> Add more highlighted languages

packages/fuels-abigen-macro/Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, tools/fuels-abi-cli/Cargo.toml
=> Bump to v0.14.1

docs/src/getting-started/basics.md, docs/src/getting-started/setup.md, docs/src/getting-started/type-safe-bindings.md, docs/src/getting-started/wallets.md, docs/src/workspaces/fuels-abigen-macro.md
=> Add ,ignore to rust blocks.

packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs
=> docs: document `get_spendable_coins` functions

packages/fuels-core/src/code_gen/abigen.rs, packages/wasm-tests/src/lib.rs
Need Parameterize trait now too.
=> Add parameterize trait

examples/wallets/src/lib.rs, packages/fuels-signers/src/wallet.rs
Ref: https://github.com/FuelLabs/pm/issues/21
=> Use SLIP-44 coin type in derivation path.

scripts/build-test-projects/src/main.rs
Should close https://github.com/FuelLabs/fuels-rs/issues/377
=> fix: excess newline in test builder

.github/workflows/gh-pages.yml
Closes #311.
Comment: not *really* sure how to check that this works though, basically copy-pasted changes from https://github.com/FuelLabs/sway/pull/2025
=> docs: split book into latest and master

docs/src/getting-started/basics.md, docs/src/getting-started/type-safe-bindings.md, docs/src/getting-started/wallets.md
Just some small improvements to the docs.
=> docs: typos and small improvements

.github/workflows/ci.yml, .github/workflows/gh-pages.yml
update github actions checkout from v2 to [v3](https://github.com/actions/checkout/releases/tag/v3.0.2)
=> ci: gh checkout v2 -> v3

docs/src/api/utils-and-helpers.md, docs/src/testing/chains.md, docs/src/testing/scripts.md, docs/src/wallets/creating-a-wallet.md, docs/src/wallets/test-wallets.md, examples/providers/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-test-helpers/src/signers.rs
A couple more updates, nits, etc., related to https://github.com/FuelLabs/fuels-rs/issues/365.
=> docs: follow-ups from the book re-org

docs/src/wallets/test-wallets.md, examples/wallets/src/lib.rs, packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/signers.rs, packages/fuels-test-helpers/src/wallets_config.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/513
Test wallets are generated using deterministic keys.
=> refactor: generate wallets with deterministic keys

docs/src/wallets/test-wallets.md, packages/fuels-test-helpers/src/lib.rs
Closes #507
I've determined some values for the number of coins and assets that lead to reasonable runtimes and added them as a recommended limit to the docs. 
I've also added a small performance improvement to `setup_multiple_assets_coins`
=> Document setup coins

.github/workflows/ci.yml, examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, packages/fuels/tests/harness.rs, packages/fuels/tests/test_projects/predicate_address/src/main.sw, packages/fuels/tests/test_projects/predicate_signatures/src/main.sw, packages/fuels/tests/test_projects/predicate_struct/src/main.sw, packages/fuels/tests/test_projects/predicate_u32/src/main.sw
closes: https://github.com/FuelLabs/fuels-rs/issues/547
=> fix: Re-enable tests blocked by stdlib's gtf integration

docs/src/README.md, docs/src/SUMMARY.md, docs/src/getting-started/connecting.md, docs/src/providers/external-node.md, examples/providers/src/lib.rs, packages/fuels/tests/harness.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/553
=> docs: add connect to testnet instructions

packages/fuels-signers/src/wallet.rs
=> refactor: expose the default derivation path to downstream crates

docs/src/getting-started/setup.md, docs/src/providers/short-lived.md, examples/contracts/Cargo.toml, examples/cookbook/Cargo.toml, examples/debugging/Cargo.toml, examples/predicates/Cargo.toml, examples/providers/Cargo.toml, examples/rust_bindings/Cargo.toml, examples/types/Cargo.toml, examples/wallets/Cargo.toml, packages/fuels-abigen-macro/Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, tools/fuels-abi-cli/Cargo.toml
- ci: update `forc` version in CI
- release: bump versions to 0.26.0
=> release: bump versions to v0.26.0

packages/fuels-core/src/code_gen/abigen.rs, packages/fuels/tests/contracts.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/642
Added the API and a test.
=> feat: add balances api to contract_instance

docs/src/getting-started/connecting.md
Closes https://github.com/FuelLabs/fuels-rs/issues/641.
=> fix: doc wording

docs/src/contracts/the-json-abi-file.md, docs/src/getting-started/contracts.md, docs/src/getting-started/predicates.md, docs/src/getting-started/setup.md
Just updating some broken links to the Sway book. These have changed recently.
=> Fix some broken links to the Sway book

packages/fuels-contract/src/contract_calls_utils.rs
closes: #727 
Just came across this gem while perusing the code.
group_by requires that the elements are sorted by the key you're grouping on.
=> bug: asset ids not collated properly.

docs/src/providers/short-lived.md, examples/contracts/Cargo.toml, examples/cookbook/Cargo.toml, examples/debugging/Cargo.toml, examples/predicates/Cargo.toml, examples/providers/Cargo.toml, examples/rust_bindings/Cargo.toml, examples/types/Cargo.toml, examples/wallets/Cargo.toml, packages/fuels-abigen-macro/Cargo.toml, packages/fuels-contract/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, tools/fuels-abi-cli/Cargo.toml
Let's release the function attributes JSON ABI change into the wild!
=> release: Bump versions to `0.32.3`

docs/src/SUMMARY.md, docs/src/scripts/index.md, docs/src/scripts/scripts.md
=> Remove empty doc section on scripts

packages/fuels-test-helpers/src/lib.rs, packages/fuels-test-helpers/src/node.rs, packages/fuels-test-helpers/src/signers.rs
This PR fixes a bug in the launch custom provider and_get_wallets function where the coin_configs and messages were being omitted from the fuel node config file. The fix involves adding the coin_configs and messages to the initial_state of the chain_config variable, as seen in the updated code:
```rust
let mut chain_config = chain_config.unwrap_or_else(|| ChainConfig::local_testnet());
chain_config.initial_state = Some(StateConfig {
coins: Some(coin_configs),
contracts: None,
messages: Some(messages),
height: None,
});
if let Some(transaction_parameters) = consensus_parameters_config {
chain_config.transaction_parameters = transaction_parameters;
}
```
closes #793
=> fix: add both chain_config and coins to node config

.github/workflows/ci.yml, examples/contracts/src/lib.rs, examples/types/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels-core/src/abi_encoder.rs, packages/fuels-core/src/function_selector.rs, packages/fuels-core/src/traits/decodable_log.rs, packages/fuels-macros/src/abigen/code_gen/abigen/bindings/contract.rs, packages/fuels-macros/src/abigen/code_gen/source.rs, packages/fuels-macros/src/utils.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-types/src/core.rs, packages/fuels/Cargo.toml, packages/fuels/tests/contracts.rs, packages/fuels/tests/logs.rs, packages/fuels/tests/wallets.rs, scripts/test-projects/src/cli.rs, scripts/test-projects/src/types.rs
This fixes the current CI issue we have.
=> Update Rust version to 1.67.0

.github/workflows/ci.yml, Cargo.toml, examples/abigen/Cargo.toml, examples/contracts/Cargo.toml, examples/cookbook/Cargo.toml, examples/debugging/Cargo.toml, examples/predicates/Cargo.toml, examples/providers/Cargo.toml, examples/rust_bindings/Cargo.toml, examples/types/Cargo.toml, examples/wallets/Cargo.toml, packages/fuels-core/Cargo.toml, packages/fuels-macros/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-signers/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, packages/fuels-types/Cargo.toml, packages/fuels/Cargo.toml, packages/wasm-tests/Cargo.toml, scripts/check-docs/Cargo.toml, scripts/test-projects/Cargo.toml
Consolidate common package metadata fields into the workspace root (e.g. version, license, authors)
=> Use workspace level package for common crate metadata values

Cargo.toml, docs/src/providers/short-lived.md
Release breaking change for new fuel-asm library
=> Fuel asm release 0.36.0

.github/workflows/ci.yml
=> ci: update `forc` version in CI

examples/cookbook/src/lib.rs, packages/fuels-programs/src/call_utils.rs, packages/fuels-programs/src/script_calls.rs, packages/fuels-signers/src/provider.rs, packages/fuels-signers/src/wallet.rs, packages/fuels-types/Cargo.toml, packages/fuels-types/src/transaction.rs
Some suggestions if you like them.
=> some pr suggestions

.github/workflows/gh-pages.yml
Found some missing spots where the cname needed to be specified for gh-pages.
=> More cnaming for gh-pages

docs/src/calling-contracts/cost-estimation.md
=> fix minor typo

packages/fuels-programs/src/contract.rs
This PR makes `load_contract` pub again.
=> fix: make `load_contract` pub

packages/fuels-programs/src/contract.rs
This fix exposes the code root for loaded contracts. The AMM contracts makes use of this.
=> feat: expose code root

Cargo.toml, packages/fuels-macros/src/setup_program_test/code_gen.rs
```
warning: /Users/emirsalkic/Documents/Git/fuels-rs/packages/fuels-accounts/Cargo.toml: `default-features` is ignored for rand, since `default-features` was not specified for `workspace.dependencies.rand`, this could become a hard error in the future
warning: /Users/emirsalkic/Documents/Git/fuels-rs/packages/fuels-accounts/Cargo.toml: `default-features` is ignored for sha2, since `default-features` was not specified for `workspace.dependencies.sha2`, this could become a hard error in the future
warning: /Users/emirsalkic/Documents/Git/fuels-rs/packages/fuels-test-helpers/Cargo.toml: `default-features` is ignored for rand, since `default-features` was not specified for `workspace.dependencies.rand`, this could become a hard error in the future
warning: …
```
=> chore: default-features warnings on cargo nightly

packages/fuels-core/src/types/transaction_builders.rs
Create a new message input depending on the message data length.
=> fix: create message type based on data length

packages/fuels-accounts/src/lib.rs, packages/fuels-accounts/src/predicate.rs, packages/fuels-accounts/src/wallet.rs
=> refactor: remove setter from account trait

packages/fuels-accounts/src/lib.rs, packages/fuels-core/src/types/wrappers/coin.rs
=> chore: update sign_and_verify test

.github/workflows/ci.yml
Saves us about 50s when running tests.
=> ci: use nextest

examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, examples/predicates/src/lib.rs, examples/providers/src/lib.rs, examples/wallets/src/lib.rs, packages/fuels/src/lib.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/providers.rs, packages/fuels/tests/scripts.rs, packages/fuels/tests/types_predicates.rs
Added `WalletUnlocked` to `prelude` for improved usability
=> feat: add `WalletUnlocked` to `prelude`

packages/fuels-core/src/types.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1034
=> fix: export `TxPointer`, `UtxoId` and `Nonce`

packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/script.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1031
=> feat: add `LogDecoder` getter for script instances

packages/fuels-core/src/types/errors.rs, packages/fuels-core/src/types/transaction_builders.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1033
=> feat: improve transaction builder error

README.md, docs/src/abigen/the-json-abi-file.md, docs/src/deploying/index.md, docs/src/getting-started.md
=> docs: fix broken links

packages/fuels-programs/src/logs.rs, packages/fuels/tests/logs.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1063
Added `data` to the error message.
=> feat: improve missing log decoder error

packages/fuels-core/src/types/core/sized_ascii_string.rs
- We're changing object IDs from `u64` to `SizedAsciiString` on the indexer https://github.com/FuelLabs/fuel-indexer/issues/1208
- With this, we need `SizedAsciiString` to `impl` a few more standard traits
- Ideally this goes out as a patch release for 0.43 and is cherry-picked wherever else it needs to go
=> chore: impl Ser + Deser + Hash for SizedAsciiString

packages/fuels-core/src/traits/tokenizable.rs
=> fix: string slice token conversion

packages/fuels-core/src/types/core/sized_ascii_string.rs
- Need one more trait implementation 🤞🏽
=> chore: `impl AsRef<[u8]> for SizedAsciiString`

examples/wallets/src/lib.rs, packages/fuels-accounts/src/predicate.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-code-gen/src/program_bindings/abigen/bindings/contract.rs, packages/fuels/tests/contracts.rs, packages/fuels/tests/predicates.rs
=> chore: make get_contract_balances return AssetId and add provider.chain_id()

.github/workflows/ci.yml, packages/fuels-code-gen/src/program_bindings/abigen.rs
=> chore: check doc links for private items in CI

docs/src/calling-contracts/low-level-calls.md, examples/contracts/src/lib.rs, examples/debugging/src/lib.rs, packages/fuels-core/src/codec/function_selector.rs, packages/fuels/tests/contracts.rs
close: https://github.com/FuelLabs/fuels-rs/issues/1099
=> feat: return result from `call_data!`

examples/providers/src/lib.rs, packages/fuels/tests/providers.rs
=> feat: update tests to beta-4

packages/fuels-accounts/src/accounts_utils.rs, packages/fuels-accounts/src/predicate.rs, packages/fuels-accounts/src/wallet.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels/tests/predicates.rs, packages/fuels/tests/providers.rs
close: https://github.com/FuelLabs/fuels-rs/issues/1123
codeveloped with: @segfault-magnet, @MujkicA and @Salka1988
=> fix!: predicate cost estimation

docs/src/running-scripts.md
=> docs: use correct method names

.github/workflows/scripts/verify_tag.sh
=> Fix dasel on CI

.github/workflows/ci.yml, Cargo.toml, packages/fuels-core/src/types/core/identity.rs
=> chore: bump `fuel-core` to `0.22.1`

packages/fuels-core/src/types/wrappers/block.rs, packages/fuels-core/src/types/wrappers/transaction_response.rs, packages/fuels-programs/src/call_utils.rs, packages/fuels-test-helpers/src/node_types.rs, packages/fuels/tests/providers.rs
Our CI is failing because of deprecation warnings.
=> chore: update deprecated functions

.github/workflows/ci.yml, examples/contracts/src/lib.rs, examples/cookbook/src/lib.rs, packages/fuels-core/src/types/core/identity.rs, packages/fuels/Forc.toml, packages/fuels/tests/contracts.rs, packages/fuels/tests/contracts/lib_contract_caller/src/main.sw, packages/fuels/tests/contracts/liquidity_pool/src/main.sw, packages/fuels/tests/contracts/token_ops/src/main.sw, packages/fuels/tests/logs.rs, packages/fuels/tests/providers.rs, packages/fuels/tests/scripts.rs, packages/fuels/tests/scripts/transfer_script/src/main.sw
=> chore: adapt to forc `0.56.0` again (CI got stuck)

Cargo.toml, docs/src/connecting/short-lived.md
=> chore: bump versions to v0.62.0

.github/workflows/ci.yml, Cargo.toml, examples/contracts/src/lib.rs, packages/fuels-accounts/src/provider/retryable_client.rs, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs, packages/fuels-core/src/types/wrappers/transaction.rs, packages/fuels-test-helpers/Cargo.toml, packages/fuels-test-helpers/src/fuel_bin_service.rs
=> chore: use `fuel-core` `0.28.0`

e2e/tests/contracts.rs, examples/contracts/src/lib.rs, packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/retryable_client.rs, packages/fuels-core/src/types/transaction_builders/script_dry_runner.rs
BREAKING CHANGE:
- Removed `dry_run_no_validation` in favor of `dry_run_opt`
- Removed `dry_run_no_validation_multiple` in favor of `dry_run_opt_multiple`
=> fix!: `dry_run` tx with non-zero base asset and tip

packages/fuels-core/src/types/transaction_builders.rs
=> fix: estimate predicates during max fee estimation

.github/workflows/ci.yml, Cargo.toml, examples/contracts/src/lib.rs, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
=> chore: use `fuel-core` `0.30.0`

docs/src/connecting/external-node.md, examples/providers/src/lib.rs
=> docs: fix testnet and faucet link

examples/providers/src/lib.rs
closes: https://github.com/FuelLabs/fuels-rs/issues/1455
=> chore: enable testnet connection test

.github/workflows/ci.yml, e2e/tests/providers.rs, examples/contracts/src/lib.rs, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs, packages/fuels-core/src/types/transaction_builders.rs, packages/fuels-core/src/types/transaction_builders/blob.rs
=> feat: default gas estimation horizon in tx builders

e2e/Forc.toml, e2e/sway/predicates/predicate_witnesses/src/main.sw, e2e/sway/predicates/swap/src/main.sw
=> chore: remove patch

e2e/sway/contracts/huge_contract/src/main.sw, e2e/sway/contracts/proxy/src/main.sw, e2e/tests/contracts.rs
Add test for storage slot initialization using a proxy contract for contract loaded with blobs.
=> feat: test storage with proxy and loader contract

packages/fuels-accounts/src/provider.rs, packages/fuels-accounts/src/provider/cache.rs
Just [some nits](https://github.com/FuelLabs/fuels-rs/pull/1569#discussion_r1909149078) from #1569 that didn't make it in the PR.
=> chore: nits from previous PR

Cargo.toml, docs/src/connecting/short-lived.md
=> chore: bump lts patch versions

Cargo.toml, docs/src/connecting/short-lived.md, packages/fuels-accounts/Cargo.toml, packages/fuels-programs/Cargo.toml, packages/fuels-test-helpers/Cargo.toml, scripts/change-log/Cargo.toml, wasm-tests/Cargo.toml
=> chore:bump lts patch version

Cargo.toml, docs/src/connecting/short-lived.md
=> chore: version bump

docs/src/calling-contracts/custom-inputs-outputs.md, docs/src/running-scripts.md
=> docs: fix custom input output snippet

e2e/tests/providers.rs
The `coin caching` test was flaky as the node returns a random number of coins when requesting a certain amount. This led the test to fail when no more coins were available.
I have increased the initial amount of coins and did not change the the test logic.
=> chore: fix flaky `coin caching` test

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
=> chore!: bump fuel core to 0 43 1

.github/workflows/ci.yml, Cargo.toml, packages/fuels-accounts/src/provider/supported_fuel_core_version.rs
=> chore: bump fuel-core to 0.43.2

Cargo.toml, docs/src/connecting/short-lived.md
Bump crate versions, prepare for new release.
=> Prepare for 0.74.0 release
